Charge command
Slimefun/Slimefun4 pull request #2309
Opened 2020-09-10 21:03 UTC by NCBPFluffyBear

## Description
Adds /sf charge, a command which charges any Rechargeable item to max charge.

## Changes
- ChargeCommand subcommand class
- Added ChargeCommand to SlimefunSubCommands
- Added slimefun.command.charge to plugin.yml
- Added success and error messages to messages_en.yml

## Related Issues
N/A

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [x] I added sufficient Unit Tests to cover my code.

2020-09-10 21:14 UTC, TheBusyBiscuit requested changes
Looks good for the most part, some minor changes I would suggest nonetheless

2020-09-10 21:14 UTC, TheBusyBiscuit commented on src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/commands/TestChargeCommand.java
> +    @DisplayName("Test if /charge charges the item the player is holding")
*/sf charge

2020-09-10 21:14 UTC, TheBusyBiscuit commented on src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/commands/TestChargeCommand.java
> +        Assertions.assertEquals(chargedItem.getItemCharge(chargedItemStack), chargedItem.getMaxItemCharge(chargedItemStack));
You should also assert the ground condition, that the charge was 0 before executing the command.
This way we can be certain that this did actually update.

2020-09-10 21:14 UTC, TheBusyBiscuit commented on src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/commands/TestChargeCommand.java
> +        final SlimefunItemStack RECHARGEABLE_ITEM = new SlimefunItemStack("RECHARGEABLE_ITEM", Material.REDSTONE_BLOCK, "Rechargeable Item", "This isn't real", LoreBuilder.powerCharged(0, 100));
Also you should pick a more unique id to prevent overlaps with future or existing unit tests, "SF_CHARGE_TEST_ITEM" for example.

2020-09-10 21:14 UTC, TheBusyBiscuit commented on src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/commands/TestChargeCommand.java
> +    @Test
This test alone is pretty good and sufficient.
*In theory* you could add more tests to achieve better coverage but I think this is enough

2020-09-10 21:14 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/ChargeCommand.java
> + * item to max.
You could be more specific here *"to the maximum value as defined by Rechargeable#getMax..."

2020-09-10 21:35 UTC, TheBusyBiscuit commented on src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/commands/TestChargeCommand.java
> +        final SlimefunItemStack RECHARGEABLE_ITEM = new SlimefunItemStack("SF_CHARGE_TEST_ITEM", Material.REDSTONE_BLOCK, "Rechargeable Item", "This isn't real", LoreBuilder.powerCharged(0, 100));
No need to mark this as final here, especially not in a Unit Test.

2020-09-10 21:35 UTC, TheBusyBiscuit commented on src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/commands/TestChargeCommand.java
> +    private class SlimefunChargeTest extends SlimefunItem implements Rechargeable {
"RechargeableItem" was probably a more appropriate class name, my previous comment was only in regard to the id, not the class name.

2020-09-10 21:38 UTC, TheBusyBiscuit submitted a review, later dismissed

2020-09-10 22:33 UTC, LinoxGH approved these changes
Looks nice and all, though the imports could use some organisation.

2020-09-11 02:31 UTC, NCBPFluffyBear commented
How would you like them organized?

2020-09-11 04:47 UTC, LinoxGH commented
> How would you like them organized?
> 

Just check out any other class

2020-09-11 05:55 UTC, LinoxGH commented
That's more like it.

2020-09-11 07:51 UTC, TheBusyBiscuit approved these changes

2020-09-11 08:15 UTC, poma123 approved these changes

2020-09-11 08:25 UTC, poma123 approved these changes

2020-09-11 08:27 UTC, poma123 approved these changes

2020-09-11 08:27 UTC, TheBusyBiscuit commented
Oh great... apparently only reviews by admins count... wow

2020-09-11 08:28 UTC, WalshyDev commented
No, they just need write perms to the repo

2020-09-11 08:31 UTC, poma123 commented
What about this Triage role thing?
![image](https://user-images.githubusercontent.com/25465545/92893314-dc8fe900-f419-11ea-8d9a-bfe83c0d6e91.png)

2020-09-11 08:31 UTC, TheBusyBiscuit commented
> No, they just need write perms to the repo

I know, I already updated that and changed the branch protection rules, it should now work.

2020-09-11 08:31 UTC, merged