Pull request for an additional customizable option in grappling hooks
Slimefun/Slimefun4 pull request #2348
Opened 2020-09-26 16:55 UTC by flaxeneel2

[+] Added a setting to allow the grappling hook to stay in inventory instead of being dropped on the floor on use

## Description
I added an item setting to allow players to set if they want the grappling hook to drop on the floor on use or just stay in the inventory. I did this because I use slimefun on a small server with friends and they complained about the grappling hooks dropping on the floor as annoying

## Changes
[+] Item Setting named "stay-in-inv-on-use"

## Related Issues
None

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2020-09-26 17:04 UTC, TheBusyBiscuit requested changes

2020-09-26 17:04 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/GrapplingHook.java
> +    private final ItemSetting<Boolean> stayininvonuse = new ItemSetting<>("stay-in-inv-on-use", false);
Please follow the naming convention for fields, this should be in "pascal case", so "stayInInvOnUse".
Other than that I think the name is a little confusing, I think something like `consumeOnUse` (which would actually be the opposite here) would make more sense and is much more user-friendly.

2020-09-26 17:04 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/GrapplingHook.java
> +            Boolean keepininv = stayininvonuse.getValue();
Please don't use the boxed `Boolean` class, use the primitive `boolean` instead.

2020-09-26 17:04 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/GrapplingHookEntity.java
> +    private final boolean keepininv;
Pascal case, so `keepInInv`, or with the suggested reversal: `wasConsumed` may be more fitting.

2020-09-27 05:13 UTC, LinoxGH approved these changes
Other than the changes TheBusyBiscuit requested, it looks fine to merge.

2020-09-27 12:55 UTC, flaxeneel2 commented
Made requested changes

2020-09-27 13:51 UTC, LinoxGH submitted a review, later dismissed

2020-09-27 16:57 UTC, TheBusyBiscuit requested changes
Just two small mistakes with comment placing, but other than that it's looking good to go!

2020-09-27 16:57 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/GrapplingHook.java
> +                        item.setAmount(item.getAmount() - 1); //If consume on use is enabled, this line will take 1 grappling hook out of player's hand
Comments should be made on the line above the code, never right next to it.

2020-09-27 16:57 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/GrapplingHookEntity.java
> +            } //If a grappling hook was consumed, then this will drop one on the floor
This comment should be made above the if-statement or inside of it.

2020-09-27 17:17 UTC, TheBusyBiscuit approved these changes
:+1:

2020-09-27 17:23 UTC, LinoxGH approved these changes

2020-09-27 18:13 UTC, merged