Changed some stuff to protected
Slimefun/Slimefun4 pull request #2366
Opened 2020-09-30 13:59 UTC by J3fftw1

## Description
Changed some stuff to protected

## Changes
Changed some stuff to protected
Added some annotations 

## Related Issues
N/A

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2020-10-01 18:59 UTC, LinoxGH requested changes

2020-10-01 18:59 UTC, LinoxGH commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin.java
> +                config.getString("options.language"));
Please break this after `this` not in the middle of a method.

2020-10-01 18:59 UTC, LinoxGH commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ButcherAndroid.java
> +            instanceof LivingEntity && !(n instanceof ArmorStand) && !(n instanceof Player) && n.isValid() && predicate.test((LivingEntity) n))) {
Please break this in a more reasonable location. Like after all `radius` args.

2020-10-01 19:20 UTC, LinoxGH approved these changes
Better.

2020-10-05 12:34 UTC, LinoxGH commented
Build is failing.

2020-10-05 12:36 UTC, J3fftw1 commented
because of the merge of master will check why

2020-10-05 13:14 UTC, J3fftw1 commented
something fucked up this branch locally for me i will make a new pr

2020-10-05 13:14 UTC, closed without merging