GPS Control Panel and GEO Scanner access checks
Slimefun/Slimefun4 pull request #2402
Opened 2020-10-07 00:50 UTC by NCBPFluffyBear

## Description
Added checks to make sure that the player attempting to access the GPS Control Panel and GEO Scanner has sufficient permissions to access them.

## Changes
- slimefun.inventory.bypass permission check
- Protection manager inventory access permission check
- Research check
- No access message

## Related Issues
N/A

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2020-10-07 01:00 UTC, TheBusyBiscuit submitted a review, later dismissed
Can't really see of any good reason why this would be useful since those aren't inventories and don't let the player do anything other than checking their own info but there's still a lot of changes to be made if this should really be a desirable change.

2020-10-07 02:17 UTC, NCBPFluffyBear commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/geo/GEOScanner.java
> +                && Slimefun.hasUnlocked(e.getPlayer(), item, false)
The entire thing? I have tested it and it allows other people to access them/activate them

2020-10-07 02:22 UTC, NCBPFluffyBear commented
> Can't really see of any good reason why this would be useful since those aren't inventories and don't let the player do anything other than checking their own info but there's still a lot of changes to be made if this should really be a desirable change.

I thought this too, but it was brought to my attention that people that had the proper GPS complexity could activate the GEO Scanners of other players. Normally wouldn't be too bad, but on skyblock, its a free boost

2020-10-07 16:45 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/geo/GEOScanner.java
> +                && Slimefun.hasUnlocked(e.getPlayer(), item, false)
The `hasUnlocked()` check is redundant, handlers aren't even called unless the Player has access to the item.

2020-10-07 18:56 UTC, Sfiguz7 approved these changes

2020-10-07 20:21 UTC, LinoxGH requested changes

2020-10-07 20:21 UTC, LinoxGH commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/geo/GEOScanner.java
> +import me.mrCookieSlime.Slimefun.api.Slimefun;
Misplaced imports.

2020-10-07 20:21 UTC, LinoxGH commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/gps/GPSControlPanel.java
> +import me.mrCookieSlime.Slimefun.api.Slimefun;
Misplaced imports.

2020-10-08 05:03 UTC, LinoxGH approved these changes

2020-10-08 12:30 UTC, Sfiguz7 approved these changes

2020-10-08 12:37 UTC, merged