Fixes damage taken from EnderBoot with Enderpearl
Slimefun/Slimefun4 pull request #2479
Opened 2020-10-15 21:54 UTC by CURVX

## Description

Fixes damage taken from EnderBoot when used with Enderpearl.
Introduces an issue, StomperBoot when used with Enderpearl, you take fall damage.

## Changes

## Related Issues

Resolves #2478 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2020-10-15 22:18 UTC, CURVX commented
Calling `onEnderPearlDamage(e)` inside `onFallDamage` should work?

2020-10-17 17:55 UTC, LinoxGH approved these changes
LGTM as long as this does fix the issue.

2020-10-18 11:20 UTC, TheBusyBiscuit requested changes
This is just very messy.
You should probably just made a new EventHandler which listens to the EntityDamageByEntityEvent and then move the code there instead of nesting it this inconsistently.

2020-10-18 17:23 UTC, TheBusyBiscuit approved these changes

2020-10-19 04:32 UTC, LinoxGH approved these changes

2020-10-19 10:49 UTC, merged