Added /slimefun drop command
Slimefun/Slimefun4 pull request #2515
Opened 2020-10-28 19:59 UTC by NCBPFluffyBear

## Description
Adds `/sf drop`, a command which drops a Slimefun item with a selectable quantity at the specified coordinates. This is helpful for scripted actions, such as mob drops.

## Changes
Added the `DropCommand` subcommand and registered under subcommands
Added `drop-item` to `messages_en.yml`
Added `DropCommandTest` unit test

## Related Issues
This was suggested on Discord so that MythicMobs could drop Slimefun items

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2020-10-29 00:09 UTC, svr333 reviewed
Two really minor remarks.
This doesnt have too many usecases but it can be really damn useful in certain areas.

2020-10-29 00:09 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/DropCommand.java
> +                    if (sfItem != null) {
I myself am not a big fan of this many nested ifs; I usually invert them and then return if the condition is not met.
Dont know how it is handled around here though.

2020-10-31 09:25 UTC, poma123 requested changes

2020-10-31 09:25 UTC, poma123 commented on src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/commands/DropCommandTest.java
> +import org.junit.jupiter.api.*;
Please don't use star imports

2020-10-31 09:25 UTC, poma123 commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/DropCommand.java
> +                if (args.length > 5) {
I'd rather check whether `args.length` is greater than 5 here, no need to check it twice

2020-10-31 09:25 UTC, poma123 commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/DropCommand.java
> + * The drop command drops a {@link SlimefunItem} of
```suggestion
 * {@link DropCommand} drops a {@link SlimefunItem} of
```

2020-10-31 09:25 UTC, poma123 commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/DropCommand.java
> +                SlimefunPlugin.getLocalization().sendMessage(sender, "messages.not-valid-amount", true, msg -> msg.replace(PLACEHOLDER_AMOUNT, args[3]));
```suggestion
                SlimefunPlugin.getLocalization().sendMessage(sender, "messages.invalid-amount", true, msg -> msg.replace(PLACEHOLDER_AMOUNT, args[3]));
```

2020-10-31 09:25 UTC, poma123 commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/DropCommand.java
> +                        SlimefunPlugin.getLocalization().sendMessage(sender, "messages.not-valid-item", true, msg -> msg.replace(PLACEHOLDER_ITEM, args[2]));
```suggestion
                        SlimefunPlugin.getLocalization().sendMessage(sender, "messages.invalid-item", true, msg -> msg.replace(PLACEHOLDER_ITEM, args[2]));
```

2020-10-31 09:35 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/DropCommand.java
> +                amount = Integer.parseInt(args[6]);
These 2 could be combined with &&

2020-10-31 09:36 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/DropCommand.java
> +                amount = Integer.parseInt(args[6]);
The ifs i mean*

2020-12-16 00:24 UTC, NCBPFluffyBear commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/DropCommand.java
> +                amount = Integer.parseInt(args[6]);
cant, one returns 0 the other returns 1

2020-12-16 11:44 UTC, WalshyDev requested changes

2020-12-16 11:44 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/SlimefunTabCompleter.java
> +import com.google.common.collect.Lists;
These are not used, remove

2020-12-16 11:44 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/DropCommand.java
> +    private static final String PLACEHOLDER_AMOUNT = "%amount%";
Always hated %% as a placeholder prefix/suffix, I prefer {} but that's my preference. {world} just looks better and for me is more readable than %world%.

Others opinions?

2020-12-16 11:44 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/DropCommand.java
> +                SlimefunPlugin.getLocalization().sendMessage(sender, "messages.drop-item", true, msg -> msg.replace(PLACEHOLDER_WORLD, args[1]).replace(PLACEHOLDER_X, args[2]).replace(PLACEHOLDER_Y,
This line is huge, please format nicely

2020-12-16 11:44 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/DropCommand.java
> +                Bukkit.getWorld(world).dropItem(new Location(Bukkit.getWorld(world), Integer.parseInt(x), Integer.parseInt(y), Integer.parseInt(z)), new CustomItem(sfItem.getItem(), amount));
There should be checks here or above that these are actually ints. `PatternUtils.NUMERIC.matcher(s).matches()`

2020-12-16 11:44 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/DropCommand.java
> +    private int parseAmount(String[] args) {
not sure why you pass an array here. Just pass a single string, can even use this for the x,y,z above.

2020-12-16 11:44 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/DropCommand.java
> +        return amount;
```suggestion
if (PatternUtils.NUMERIC.matcher(s).matches()) {
    return OptionalInt.of(Integer.parseInt(s));
} else {
    return OptionalInt.empty();
}
```

2020-12-16 11:44 UTC, WalshyDev commented on src/main/resources/languages/messages_en.yml
> -  bee-suit-slow-fall: '&eYour Bee Wings will help you to get back to the ground safe and slow'
don't remove this

2020-12-16 11:44 UTC, WalshyDev commented on src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/commands/DropCommandTest.java
> +        }
There also should be tests to make sure validation works, so non-extistent world, invalid coords, invalid item, too high amount/0, etc

2021-01-25 20:13 UTC, TheBusyBiscuit commented
Closing this since there hasn't been a response in over a month now.

2021-01-25 20:13 UTC, closed without merging