Fixed #121. Not good, but useful.
Slimefun/Slimefun4 pull request #2540
Opened 2020-11-05 07:12 UTC by ALiangLiang

## Description

It's fixed the oldest issue #121. But I think the PR is just a suggestion or prototype. Need someone review and edit it to be more beautiful. I am not sure if this will affect performance.

## Changes

The biggest changes is to check the destinations before withdraw the input target [here](https://github.com/ALiangLiang/Slimefun4/blob/fix%2F%23121/src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNetworkTask.java#L105).

## Related Issues

Resolves #121 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2020-11-19 10:59 UTC, TheBusyBiscuit commented
Just here to inform you that the review of this PR will still take a while.
You are trying to merge this into an experimental branch which is subject of another PR, which does complicate this a bit.
Cargo as a whole is just very delicate and takes way longer to review anyway, it's a mess...

So just don't worry, this wasn't forgotten, it will simply take some time till we get there.

2020-11-19 14:18 UTC, ALiangLiang commented
@TheBusyBiscuit Never mind. I know the cargo system is messy... so I try to fix it on a better edition of cargo on [`optimization/cargo-filters`](https://github.com/Slimefun/Slimefun4/tree/optimization/cargo-filters). If the branch is not merged, I can edit the code for the master branch.

2020-12-10 22:10 UTC, svr333 requested changes
This is an initial review (didnt really check the code yet, only glanced over it) but there are a few typos that need addressing, especially the one in the name of the method.

Overall you also have quite a few comments and I feel like several of them are quite redundant.

2020-12-10 22:10 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java
> +     *            The target item stack and slot we want to withdraw.
Please use `{@Link name}` to refer to a certain thing in the code.
On the first two comments you also practically repeat the same thing twice

2020-12-10 22:10 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java
> +     * @return If withdraw successfully, return the target ItemStackAndInteger.
```suggestion
     * @return If withdrawn successfully, return the target ItemStackAndInteger.
```

2020-12-10 22:10 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNetworkTask.java
> +        // List all output nodes with same frequency
```suggestion
        // List all output nodes with the same frequency
```

2020-12-10 22:10 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNetworkTask.java
> +            // If there is no remaining, it is null.
```suggestion
            // If there is nothing remaining, it will be null.
```

2020-12-10 22:10 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoNetworkTask.java
> +        // Distributed but some items left
Comment is redundant because the previous one already explains it

2021-01-26 00:01 UTC, TheBusyBiscuit commented
Closing this since there hasn't been a response in over a month now.

2021-01-26 00:01 UTC, closed without merging