Add Tier 3 Electric Ore Grinder
Slimefun/Slimefun4 pull request #2599
Opened 2020-12-06 01:07 UTC by svr333

## Description
Add a tier 3 Electric Ore Grinder (reinforced plates, blistering ingots, T2 electric ore grinders and heating coils)
![image](https://user-images.githubusercontent.com/35664724/101268748-2c572580-3767-11eb-9821-42f387d723c1.png)

## Changes
- Add tier 3 Electric Ore Grinder to ResearchSetup of endgame grinding
- Add new SlimefunItemStack to `SlimefunItems.java`
- Add new ElectricOreGrinder to `SlimefunItemSetup.java`

## Feedback
I was very unsure about the recipe, seeing as the recipe for the Tier 2 Ore Grinder is also very pricy.
I was thinking of reducing their cost but instead I increased this cost.
Very open for discussion though!

## Checklist
- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2020-12-06 11:59 UTC, TheBusyBiscuit requested changes

2020-12-06 11:59 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
> +        .setEnergyConsumption(90)
This should be 45, otherwise it wouldn't be inline with the lore you set.
This is per tick, not per second.

2020-12-07 11:24 UTC, hex8F commented
Just 2 cents about recipe/power cost - for me, there is no reason to ever craft this machine.
2 Electric Ore Grinders IIs process items the same speed as proposed Grinder III while being cheaper AND requiring less power (2x30 J vs 90 J).

2020-12-08 12:40 UTC, svr333 commented
> 
> 
> Just 2 cents about recipe/power cost - for me, there is no reason to ever craft this machine.
> 2 Electric Ore Grinders IIs process items the same speed as proposed Grinder III while being cheaper AND requiring less power (2x30 J vs 90 J).

Well this is the same with all the other tier 3 machines, they use more power than 2 tier 2s combined and they start using blistering ingots in their recipes, seeing as the tier 2 of this machine already used blistering ingots, I made this one even more expensive.
I did think about making tier 2 cheaper and change it from endgame to advanced machine but I cant make that decision alone

2020-12-09 21:33 UTC, Sfiguz7 submitted a review, later dismissed
I mean other than the recipe discussion (which I agree is less efficient but as all Tier III are, I've always assumed their purpose was mostly dust farm compactness in the late game when you have enough production already rather than efficiency so I don't mind the one you used) it looks good to me.

2020-12-09 23:59 UTC, hex8F commented
Re: recipe discussion

Sure, compactness is a good reason, but I'm pretty sure every Tier III is more efficient per item (important bit that I've of course forgot to type :P ).
Also, grand total of 5 Blistering Ingots is really rough to create on servers that don't run adminshops/electric spawners, especially  since you can craft 5 Grinders II using them.

2020-12-10 16:00 UTC, svr333 commented
Well I would suggest the following then:

RP HC RP
EO BI EO
RP HC RP

with RP being Reinforced Plates, HC being Heating Coils, EO being Electric Ore Grinder tier 2 and BI being a Blistering ingot

2020-12-17 20:06 UTC, svr333 commented
Seeing as no one objected, I pushed my proposal.

2020-12-18 12:22 UTC, Sfiguz7 approved these changes
Continues to be fine by me, I've already expressed my thoughts above

2021-01-25 15:37 UTC, WalshyDev approved these changes
LGTM

2021-01-25 23:55 UTC, TheBusyBiscuit approved these changes

2021-01-25 23:56 UTC, merged