Added PR labels
Slimefun/Slimefun4 pull request #2627
Opened 2020-12-13 17:29 UTC by WalshyDev

## Description
Made this action forever ago, was meant to add it in Hacktoberfest but... yeah.

Anyway, this adds labels to PRs based on the branch prefix. This is good for categorisation and helpful for people like myself for which PRs to look at first. We should add more labels but I thought these were some basic starting ones.

## Changes
* new workflow file to add labels

## Related Issues
N/A

## Checklist

- [X] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2020-12-21 01:34 UTC, svr333 submitted a review, later dismissed
Nice addition, wont trigger many if any false positives
Im all for it

2020-12-21 20:40 UTC, Sfiguz7 approved these changes
Mr Blob forced me at gunpoint, please he has my children




LGTM

2020-12-22 14:51 UTC, TheBusyBiscuit requested changes
I'll be honest and say I am not really a big fan of this, seems quite unnecessary and I definitely would veto against this being a requirement for PRs.

I am not a big fan of having too many labels, but if you guys find this helpful, sure, we can always manually label PRs, they come in rare enough for that to be not too much of a stretch.

2020-12-22 14:51 UTC, TheBusyBiscuit commented on .github/workflows/pr-labels.yml
> +    runs-on: ubuntu-latest
Missing job name.

2020-12-22 14:51 UTC, TheBusyBiscuit commented on .github/workflows/pr-labels.yml
> +      - uses: WalshyDev/pr-labels@v1
Missing name for this step

2020-12-22 14:51 UTC, TheBusyBiscuit commented on .github/workflows/pr-labels.yml
> +          token: "${{ secrets.GITHUB_TOKEN }}"
We can use the token for @TheBusyBot here.

```suggestion
          token: "${{ secrets.ACCESS_TOKEN }}"
```

2020-12-22 14:51 UTC, TheBusyBiscuit commented on .github/workflows/pr-labels.yml
> +          feature: 'New Feature'
emoji? :eyes:

2020-12-22 14:51 UTC, TheBusyBiscuit commented on .github/workflows/pr-labels.yml
> +          chore: 'Chore'
emoji? :eyes:

2020-12-22 14:51 UTC, TheBusyBiscuit commented on .github/workflows/pr-labels.yml
> +          performance: '🛠️ Performance Improvement'
Redundant. I think we should remove one of those, or we could approach it with a regular expression.

2021-01-24 17:21 UTC, TheBusyBiscuit commented
Would be awesome if the changes will be addressed, I took the liberty to add labels for it already.

* "🧹 Chores"
* "💡 Performance Optimization"
* "🎈 Feature"
* "✨ Fix"

2021-01-25 11:42 UTC, TheBusyBiscuit reviewed
I fixed the given issues myself now.
One suggestion I still have would be have an output for this action, something like "applied-label".
Then we could do a null check on this and perhaps make TheBusyBot leave a comment like "Hey, we recommend you to use this branch naming convention..."

2021-01-25 15:46 UTC, WalshyDev commented
Sure, looking into that now

2021-01-25 16:14 UTC, WalshyDev commented
![image](https://user-images.githubusercontent.com/8492901/105732486-66070a00-5f28-11eb-9961-8ef9834c7027.png)

Yeah :sunglasses:

2021-01-25 16:21 UTC, WalshyDev commented
Pushed v1.1 and updated the workflow file

Example of usage is on the release page: https://github.com/WalshyDev/pr-labels/releases/tag/v1.1

2021-01-25 17:18 UTC, TheBusyBiscuit approved these changes

2021-01-25 17:18 UTC, merged