Feature/experimental talismans
Slimefun/Slimefun4 pull request #2645
Opened 2020-12-22 21:53 UTC by svr333

## Description
Implement 2 new talismans, Talisman of the Wise and Talisman of the Resurrected. Also refactors the Talisman class quite a bit.

Regarding my Testing results below, I dont know if Ender Talismans are supposed to work in inventories, otherwise the only thing needed to fix is the ability to right click the Ender variant of the Talisman of the Resurrected.

## Changes
- Everything from the old PR
- Add a return statement so it doesnt send 2 messages

## Testing Results
@ ![img](https://cdn.discordapp.com/emojis/725813223797817372.png?v=1)

I did some thorough testing and came to the following results:
- Ender Talismans only works in enderchest, not in inventory
- Right clicking on the Ender Talisman of the Resurrected does not set a respawn point
- Both variants of the Talismans of the Anvil, Miner, Wise and Traveller work (I assume the rest works too but I didnt test all of them)

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2020-12-23 04:21 UTC, MasterPearl commented
Hey. I am a little confused can someone explain how this plugin works? I am still learning.

2020-12-23 09:01 UTC, J3fftw1 commented
> Hey. I am a little confused can someone explain how this plugin works? I am still learning.

Join the discord this is not the place to ask

2021-01-06 16:08 UTC, WalshyDev requested changes
Quick look through. You can change the Location storage to just a simple `long` with BlockPosition. Makes it much easier and saves some nice memory and disk space.

2021-01-06 16:08 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/talismans/ResurrectedTalisman.java
> +    private JsonObject createJsonFromLocation(@Nonnull Location loc) {
I would recommend just changing this. You can use BlockPosition and just store the long.

2021-01-06 16:08 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
> +            SlimefunPlugin.runSync(() -> PaperLib.teleportAsync(player, getSafeRespawnLocation(talisman, player)), 2);
Any reason you delay this 2 ticks? This event will keep firing as the player is on half a heart and keeps getting damage from the void.

2021-01-24 16:02 UTC, TheBusyBiscuit commented
I think I will "cherry-pick" merge the Talisman of the Wise already, seems very useful and stable enough to make it into the /master/ branch.

2021-01-24 17:06 UTC, merged

2021-01-24 17:08 UTC, TheBusyBiscuit commented
@svr333 For the Talisman of the Resurrected, you may need to make a new PR and revert the latest commit to `master`