(API) Multi-Categories
Slimefun/Slimefun4 pull request #2681
Opened 2021-01-03 19:50 UTC by TheBusyBiscuit

## Description

This PR adds the `MultiCategory` which itself can store several `SubCategories`.
This will likely not be used inside Slimefun itself. But is relevant for many Addon Creators who wanted a feature like this.

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-01-10 10:02 UTC, Sfiguz7 approved these changes
Oh yes please, some Addons will be able to use this for a much tidier view I love it
As for the code, couldn't spot any issues

2021-01-28 15:51 UTC, svr333 approved these changes
Seems good to me, can't wait to see this used in addons

2021-01-31 18:33 UTC, WalshyDev requested changes

2021-01-31 18:33 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/MultiCategory.java
> +    public boolean isVisible(Player p, PlayerProfile profile, SlimefunGuideMode mode) {
```suggestion
    @Override
    ParametersAreNonnullByDefault
    public boolean isVisible(Player p, PlayerProfile profile, SlimefunGuideMode mode) {
```

2021-01-31 18:33 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/MultiCategory.java
> +    public void open(Player p, PlayerProfile profile, SlimefunGuideMode mode) {
```suggestion
    @Override
    ParametersAreNonnullByDefault
    public void open(Player p, PlayerProfile profile, SlimefunGuideMode mode) {
```

2021-01-31 18:33 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/SubCategory.java
> +    public final boolean isHidden(Player p) {
@Nonnull

2021-01-31 18:33 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/CheatSheetSlimefunGuide.java
>      @Override
```suggestion
    @Override
    @ParamParametersAreNonnullByDefault
```

2021-01-31 18:44 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/MultiCategory.java
> +            ChatComponent chatComponent = new ChatComponent(ChatUtils.crop(ChatColor.DARK_GREEN, ItemUtils.getItemName(category.getItem(p))) + "\n");
The Book variant should be removed here anyway...

2021-01-31 18:45 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/MultiCategory.java
> +            ChatComponent chatComponent = new ChatComponent(ChatUtils.crop(ChatColor.DARK_GREEN, ItemUtils.getItemName(category.getItem(p))) + "\n");
oh, you reviewed an outdated diff, that's why

2021-01-31 18:47 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/categories/MultiCategory.java
> +            ChatComponent chatComponent = new ChatComponent(ChatUtils.crop(ChatColor.DARK_GREEN, ItemUtils.getItemName(category.getItem(p))) + "\n");
oh, I had an old review still :lul:

2021-02-09 07:28 UTC, Hellcode48 commented
I'm super stoked to see this done

2021-02-23 07:53 UTC, Sfiguz7 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/CheatSheetSlimefunGuide.java
>      @Override
ParamParameters :p

2021-02-23 07:54 UTC, Sfiguz7 approved these changes
Walshy's annotations to save some technical debt but everything looks good to me

2021-03-04 08:06 UTC, Sfiguz7 approved these changes
LGTM

2021-03-11 00:55 UTC, WalshyDev approved these changes
LGTM

2021-03-11 00:55 UTC, merged