Fixes #2677
Slimefun/Slimefun4 pull request #2831
Opened 2021-02-20 12:19 UTC by Thehrz

## Description
Fixes #2677 

## Changes
Added judgment on potion for SlimefunUtils#isItemSimilar()

## Checklist
- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-02-20 12:29 UTC, WalshyDev requested changes
CraftMetaPotion does not override #equals (however they do have #hashCode...). This means it will fallback to CraftMetaItem's equals may result in it being incorrect. Not sure if their `return CraftItemFactory.instance().equals(this, (ItemMeta) object);` will do some weirdness to make it compare correctly.

Just something to note

2021-02-20 12:29 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
> +        }else if (!checkLore) {
space missing
```suggestion
        } else if (!checkLore) {
```

2021-02-27 22:48 UTC, svr333 submitted a review, later dismissed
Looks good, keep walshys remark in mind though

2021-03-04 11:39 UTC, Sfiguz7 approved these changes
LGTM

2021-03-16 22:57 UTC, LinoxGH approved these changes

2021-03-22 21:27 UTC, svr333 approved these changes

2021-03-22 21:38 UTC, TheBusyBiscuit requested changes
I am not actually requesting any changes yet.
I just wanna prevent this from being merged until I took a look at it since this modifies one of the most frequently used methods within Slimefun.

2021-04-03 08:32 UTC, TheBusyBiscuit requested changes

2021-04-03 08:32 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
> +            return ((PotionMeta) itemMeta).getBasePotionData().hashCode() == ((PotionMeta) sfitemMeta).getBasePotionData().hashCode();
This overrides any lore checks, so if we have two potions with the same potion data but different lore, they will still pass as "equal", even when the `checkLore` parameter is set to true.

Furthermore `.hashCode()` should not really be used for comparisons like this, there is nothing wrong with using `.equals()` here instead.
Note that  `.hashCode()` and `.equals()` always co-exist with each other and are never overridden by themselves only.
Or as Yoda would put it:

> Always two there are, no more, no less.

2021-04-27 09:49 UTC, TheBusyBiscuit commented
Closing this since there hasn't been any response in over three weeks.

2021-04-27 09:49 UTC, closed without merging