Added ExplosiveToolBreakBlockEvent
Slimefun/Slimefun4 pull request #2859
Opened 2021-03-03 15:28 UTC by GallowsDove

## Description
Added ExplosiveToolBreakBlockEvent triggered by an explosive tool breaking a block.
I need it for my addon, as it can currently break blocks without me having any event to catch.

## Changes
Added ExplosiveToolBreakBlockEvent, made it Cancellable and edited ExplosiveTool to reflect that

## Related Issues
null

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-03-03 15:30 UTC, WalshyDev commented
We should have a way to get the `ExplosiveTool` getExplosiveTool. We also should probably show all the blocks being destroyed

2021-03-03 17:52 UTC, Mooy1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/events/ExplosiveToolBreakBlockEvent.java
> +        this.cancelled = true;
I think you meant to put b instead of true here

2021-03-03 17:59 UTC, WalshyDev requested changes

2021-03-03 17:59 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/events/ExplosiveToolBreakBlockEvent.java
> +
remove these empty lines

```suggestion
```

2021-03-03 17:59 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/events/ExplosiveToolBreakBlockEvent.java
> +     *
nitpick: remove empty line in these javadocs. it isn't needed

2021-03-03 17:59 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
> +        ArrayList<Block> blocksToDestroy = new ArrayList<>();
List, you should use the interface as typing rather than implementation

2021-03-03 17:59 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
> +        if (!event.isCancelled()){
space after ending brackets

```suggestion
        if (!event.isCancelled()) {
```

2021-03-10 00:03 UTC, TheBusyBiscuit requested changes

2021-03-10 00:03 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/events/ExplosiveToolBreakBlockEvent.java
> +public class ExplosiveToolBreakBlockEvent extends PlayerEvent implements Cancellable {
Technically this should be *Blocks* (plural) since multiple blocks are broken. The singular could imply that this was called for every single block.

2021-03-10 00:03 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/events/ExplosiveToolBreakBlockEvent.java
> +        this.cancelled = b;
No need for nonsencial abbreviations here
```suggestion
    public void setCancelled(boolean cancel) {
        this.cancelled = cancel;
```

2021-03-10 00:03 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/events/ExplosiveToolBreakBlockEvent.java
> +    public ItemStack getTool() {
I think "tool" vs. "explosive tool" is quite confusing naming.
This method returns the item the player is holding, so the name should reflect that.
```suggestion
    public ItemStack getItemInHand() {
```

2021-03-10 00:03 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/events/ExplosiveToolBreakBlockEvent.java
> +        super(player);
The parameters are marked as nonnull, so you should add `Validate.notNull(x, msg)` validations here.

2021-03-11 00:42 UTC, WalshyDev approved these changes

2021-03-11 10:15 UTC, TheBusyBiscuit approved these changes

2021-03-11 10:17 UTC, merged