Fixes #2942
Slimefun/Slimefun4 pull request #2956
Opened 2021-04-14 11:25 UTC by WalshyDev

## Description
In the case of calling `Localization#getMessage(String)` there was no override in SlimefunLocalization meaning that no fallback was done.

Also fixed an issue with an invalid validation (). Added some extra validates too.

## Changes
* Fixes #2942 
* Fixed incorrect Validate
* Added more Validates

## Related Issues
Resolves #2942 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-04-14 16:05 UTC, TheBusyBiscuit approved these changes
LGTM, so basically the fallback was in the overloaded method but not in the non-player one? :LUL:

Did you test this?

2021-04-15 10:58 UTC, WalshyDev commented
> LGTM, so basically the fallback was in the overloaded method but not in the non-player one? :LUL:
> 
> Did you test this?

Yep exactly. This method wasn't used anywhere before the recent changes to max level. So, this only has 2 usages (enchanter + disenchanter). Makes sense why we didn't see it until now.

and yes, this was tested and works perfectly.

2021-04-15 11:01 UTC, Sfiguz7 submitted a review, later dismissed

2021-04-15 11:13 UTC, TheBusyBiscuit requested changes

2021-04-15 11:13 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/services/localization/SlimefunLocalization.java
>      public abstract Language getDefaultLanguage();
Both of these are nullable.

2021-04-16 12:08 UTC, TheBusyBiscuit reviewed
LGTM, just one question

2021-04-16 12:08 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/services/localization/SlimefunLocalization.java
> +
Why no validation for the message key?

2021-04-17 07:40 UTC, WalshyDev commented
Happy RC day!

2021-04-17 07:40 UTC, TheBusyBiscuit commented
I was literally just about to hit push on `stable`...

2021-04-17 07:41 UTC, WalshyDev commented
Nuh! merge this first

2021-04-17 07:41 UTC, WalshyDev commented
Sorry I was late on this, I was super caught up. Busy today too but just remembered it's RC day so cranked this out before I get ready

2021-04-17 07:42 UTC, TheBusyBiscuit approved these changes
Looks good to me.

@Sfiguz7 Approve pls

2021-04-17 07:43 UTC, TheBusyBiscuit commented
> Sorry I was late on this, I was super caught up. Busy today too but just remembered it's RC day so cranked this out before I get ready

I really wanted this to be merged before RC too, I will delay the release until tomorrow so we can get a bit of time for potential bug reports inbetween this and the release.

2021-04-17 07:44 UTC, Sfiguz7 approved these changes

2021-04-17 07:46 UTC, merged