Add Block of Coal -> Carbon recipe to the Carbon Press and Compressor
Slimefun/Slimefun4 pull request #2963
Opened 2021-04-17 11:30 UTC by martinbrom

## Description

Compressor and Carbon Press now accept 8 coal blocks and use those to craft 9 carbon. This is useful when moving and processing large amounts of coal.
Carbon Press coal block recipe gives no processing speed or product amount advantage over using the standard coal one. (9x slower, 9 carbon).

## Changes

- Added recipe to the Compressor multiblock
- Added recipe to the CarbonPress machine

## Related Issues

none, Discord suggestion 915

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-04-17 11:36 UTC, TheBusyBiscuit requested changes
Looks good, thank you.
Just one small error I noticed.

2021-04-17 11:36 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/CarbonPress.java
> +        registerRecipe(180, new ItemStack[] { new ItemStack(Material.COAL_BLOCK, 8) }, new ItemStack[] { new CustomItem(SlimefunItems.CARBON, 9) });
```suggestion
        registerRecipe(180, new ItemStack[] { new ItemStack(Material.COAL_BLOCK, 8) }, new ItemStack[] { new SlimefunItemStack(SlimefunItems.CARBON, 9) });
```

2021-04-17 12:45 UTC, martinbrom commented
Sorry but I amended the changes out of habit instead of pushing another commit
PS: should the next line where the recipe for compressed carbon is defined also use 'SlimefunItemStack' instead of 'CustomItem' then?

2021-04-17 21:18 UTC, TheBusyBiscuit approved these changes
LGTM

> PS: should the next line where the recipe for compressed carbon is defined also use 'SlimefunItemStack' instead of 'CustomItem' then?

Ideally, yes. Feel free to change that too if you want, otherwise we will change it some day eventually anyway. We generally use our own `ItemStack` implementation nowadays to automatically read and apply CustomModelData and such.

2021-04-17 21:26 UTC, martinbrom commented
> Feel free to change that too if you want

I will add it at some point with a few other cleanup things I found while browsing some of the classes

2021-04-23 11:41 UTC, TheBusyBiscuit commented
@Slimefun/code-reviewers Guys, this still needs a second review... :eyes:

2021-04-23 11:43 UTC, WalshyDev approved these changes
I assumed we were waiting on @martinbrom per his last message, if not though LGTM

2021-04-23 11:45 UTC, TheBusyBiscuit commented
I understood that as in "in a future PR".
Rightfully so though, since this isn't really in scope of this feature anyway.
Anyway, thanks for the PR. I am gonna merge it then!

2021-04-23 11:46 UTC, merged