Main Menu Page History Fix
Slimefun/Slimefun4 pull request #2993
Opened 2021-04-26 23:17 UTC by Mooy1

## Description
Keeps the main menu page history saved

## Proposed changes
Added a main menu page field to GuideHistory, added getters and setters. When the guide is opened, it sets the main menu page to the page it was opened to.

## Related Issues (if applicable)
Fixes #2593

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-04-26 23:47 UTC, TheBusyBiscuit requested changes
Nice little fix actually, thanks!
Just one remark I'd like to leave.

2021-04-26 23:47 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
> +        profile.getGuideHistory().setMainMenuPage(page);
The guide history should not be touched in non-survival mode.
Can also store the guide history as a variable here if we're being honest.
```suggestion
        if (isSurvivalMode()) {
            profile.getGuideHistory().clear();
            profile.getGuideHistory().setMainMenuPage(page);
        }
```

2021-04-27 07:59 UTC, TheBusyBiscuit requested changes

2021-04-27 07:59 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/GuideHistory.java
> +import java.util.Objects;
Unused import

2021-04-27 07:59 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
> +            profile.getGuideHistory().setMainMenuPage(page);
We could store `GuideHistory` as a variable here.

2021-04-27 14:28 UTC, TheBusyBiscuit approved these changes
LGTM

2021-04-30 10:31 UTC, svr333 approved these changes
LGTM

2021-04-30 10:36 UTC, merged