Add a new header pointing to existing issues and Discord
Slimefun/Slimefun4 pull request #3006
Opened 2021-04-30 15:32 UTC by WalshyDev

Mentioned existing issues, mentioned testing on dev if RC and mentioned Discord

2021-04-30 15:35 UTC, WalshyDev commented
oooo, we could even make checkboxes which are like "I have checked for existing issues" and "I am reporting for the latest DEV version"

2021-04-30 15:38 UTC, TheBusyBiscuit requested changes
Not a huge fan of the wording on this.
And we already have the discord advertised in the screen before creating the issue.

Also, before we adding to much clutch to this.
I think we should create another feedback form, ask our users for opinion and discuss the structure of this with the @Slimefun/bug-testers team.

2021-04-30 15:42 UTC, WalshyDev commented
To the triage team (or anyone else wanting to review), the form of this PR can be found here: https://github.com/Slimefun/Slimefun4/blob/issue-forms-header/.github/ISSUE_TEMPLATE/bug-report-beta.yaml

2021-04-30 15:52 UTC, variananora commented
> Not a huge fan of the wording on this.

Yeah, it seems a little off to me.

Also idk if 'related plugins' should have another section to this...
Otherwise it's nicer to have this segmented.

2021-04-30 17:59 UTC, brettsaunders21 commented
I know I haven't been very active, but I agree with @variananora.

With the old format, it made more sense, but with this one it's a little odd to list related plugins under "Slimefun version".

I think people will just miss out the plugin's part.

2021-04-30 18:12 UTC, TheBusyBiscuit commented on .github/ISSUE_TEMPLATE/bug-report-beta.yaml
> +      and see if others experience a similar issue.
Yes

2021-04-30 18:13 UTC, TheBusyBiscuit submitted a review, later dismissed
I made some changes to this.

What do you all think?

2021-04-30 18:29 UTC, WalshyDev commented
![image](https://user-images.githubusercontent.com/8492901/116738440-577a3400-a9ea-11eb-8581-f4e2ce47a69b.png)

In the checkboxes you forgot to put the stuff under attributes

2021-04-30 18:31 UTC, WalshyDev commented
![image](https://user-images.githubusercontent.com/8492901/116738588-90b2a400-a9ea-11eb-94ac-679ad4229995.png)
as I mentioned before, this is going on a new line, I dislike this... but you said "yes" so err... i guess you can decide to change or not

2021-04-30 18:34 UTC, TheBusyBiscuit commented
> ![image](https://user-images.githubusercontent.com/8492901/116738588-90b2a400-a9ea-11eb-94ac-679ad4229995.png)
> as I mentioned before, this is going on a new line, I dislike this... but you said "yes" so err... i guess you can decide to change or not

Fine... I changed it.

2021-04-30 18:35 UTC, TheBusyBiscuit approved these changes
opinions?

2021-04-30 18:40 UTC, brettsaunders21 commented
I think that looks a lot better. Checkboxes are definitely a good idea.

Bit picky but:
"Videos and Screenshots help illustrate issues the best."

Sounds better in my opinion as:
"The best way to help illustrate the issue is through Videos and Screenshots."

2021-04-30 18:41 UTC, WalshyDev reviewed
I'm happy.

As a sidenote, this: 
![image](https://user-images.githubusercontent.com/8492901/116739764-feab9b00-a9eb-11eb-9cac-7d9267bb4c52.png)

I have sent my support for this to be added

2021-04-30 18:41 UTC, TheBusyBiscuit commented
> I'm happy.
> 
> As a sidenote, this:
> ![image](https://user-images.githubusercontent.com/8492901/116739764-feab9b00-a9eb-11eb-9cac-7d9267bb4c52.png)
> 
> I have sent my support for this to be added

In the meantime, they can just be considered single-quotes I guess /shrug

2021-04-30 18:42 UTC, TheBusyBiscuit commented
> I think that looks a lot better. Checkboxes are definitely a good idea.
> 
> Bit picky but:
> "Videos and Screenshots help illustrate issues the best."
> 
> Sounds better in my opinion as:
> "The best way to help illustrate the issue is through Videos and Screenshots."

Alright, thanks!

2021-04-30 18:43 UTC, TheBusyBiscuit submitted a review, later dismissed

2021-04-30 22:40 UTC, TheBusyBiscuit approved these changes

2021-04-30 23:14 UTC, brettsaunders21 approved these changes

2021-04-30 23:15 UTC, brettsaunders21 approved these changes

2021-05-01 02:50 UTC, variananora commented
LGTM but should we add another checkbox to make sure their not using modified version of slimefun or something like that?

2021-05-01 08:17 UTC, TheBusyBiscuit commented
> LGTM but should we add another checkbox to make sure their not using modified version of slimefun or something like that?

Added.

2021-05-01 08:18 UTC, TheBusyBiscuit approved these changes
I will merge this for now just to see the results but this will still be a beta and I will continue gathering feedback on discord.

2021-05-01 08:18 UTC, merged