Fixed explosive tool handling for blocks with a BlockBreakHandler
Slimefun/Slimefun4 pull request #3038
Opened 2021-05-08 06:41 UTC by Mooy1

## Description
Previously, a slimefun block could only be destroyed by an explosive tool's blast radius if the item had no
BlockBreakHandler. Now, it will correctly break it as long as the handler doesn't cancel the dummy event, or if there is no handler.

## Proposed changes
Moved callItemHandler out of if statement

## Related Issues (if applicable)
Fixes #3036 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-05-09 21:09 UTC, TheBusyBiscuit requested changes

2021-05-09 21:09 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
> +            if (!dummyEvent.isCancelled()) {
Some comments outlining why this is a wanted behaviour would be nice

2021-05-09 22:41 UTC, Mooy1 commented
If a block had a break handler to drop items in inv, and was broken indirectly by explosive pick, it would drop the items in inventory but not actually break.

2021-05-09 22:43 UTC, Mooy1 commented
Also, the dummy event being added was useless because if the item had a handler, the if would be false, and if the item had no handler, the event wouldn't be used.

2021-05-10 09:53 UTC, TheBusyBiscuit commented
Comments as in comments in the code...

2021-05-10 15:51 UTC, Mooy1 commented
Oh :notlikethis:

2021-05-10 18:57 UTC, Mooy1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
> +            // Call the BlockBreakHandler if the block has it to allow for cancelling.
I was trying to fix an issue with my addon but it does happen to fix that aswell, should I still only mark it as fixing that issue? Its more of a general fix.

2021-05-10 20:08 UTC, TheBusyBiscuit approved these changes
Much better

2021-05-10 20:10 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
> +            // Call the BlockBreakHandler if the block has it to allow for cancelling.
It is fine to list just that one here, we can track it this way since there is a concrete issue id.

Also did you test these changes yet?

2021-05-10 20:19 UTC, WalshyDev commented
@TheBusyBiscuit auto squash is failing FYI

2021-05-10 20:20 UTC, merged

2021-05-10 20:23 UTC, Mooy1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ExplosiveTool.java
> +            // Call the BlockBreakHandler if the block has it to allow for cancelling.
Just tested it, works fine and fixes that issue