Change the way the TickerTask tracks Blocks
Slimefun/Slimefun4 pull request #3043
Opened 2021-05-11 16:29 UTC by md5sha256

## Description

As per a discussion in the SF discord, this PR removes the use of explicit locks used in TickerTask. 
I'm not a massive fan of the implementation of `TickingBlocks` as it is right now. Currently its just been wrapped (mutex) so it isn't that much better for performance than it was before (might even be worse on that end). However, we now map the world to a long as opposed to `ChunkPosition --> Set<Location>` which means the memory footprint is considerably lower. 

## Proposed changes

- Add `TickingBlocks`, a class that serves as an accessor/wrapper for a `Map<World, Set<Long>>`. In other words, a `BlockPositionSet`. 
- Removes the public getters for the `tickingLocations`
- Swap out the `Lock` + `Map<ChunkPosition, Set<Location>>` for `TickingBlocks`
- Added relevant docs

## Related Issues (if applicable)

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-06-03 16:50 UTC, TheBusyBiscuit requested changes

2021-06-03 16:50 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickingBlocks.java
> +final class TickingBlocks {
Not a fan of this name tbh.
Perhaps `TickerCollection`?

2021-06-03 16:50 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickingBlocks.java
> +        return blocks.computeIfAbsent(world, (unused) -> Collections.synchronizedSet(new HashSet<>()));
Don't put braces around a single variable in a lambda expression
```suggestion
        return blocks.computeIfAbsent(world, x -> Collections.synchronizedSet(new HashSet<>()));
```

2021-06-03 16:50 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickingBlocks.java
> +    }
sum javadocs? :D

(No necessity, just nice to have)

2021-06-03 16:50 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickingBlocks.java
> +    }
These methods seem to be unused and are public, yet this class isn't even public and the TickerTask provides no getter for this object anyway.

2021-06-04 10:55 UTC, md5sha256 commented
I've resolved the comments. That being said I've also changed the implementation of `TickingCollection` to use a guava `Cache` as that offers better concurrent performance whilst also supporting weak keys. Alongside biscuit, could @WalshyDev also have a look through?

2021-06-04 10:58 UTC, TheBusyBiscuit commented
> Alongside biscuit, could @WalshyDev also have a look through?

I am not enough :FeelsBadMan:

2021-06-04 10:59 UTC, md5sha256 commented
> > Alongside biscuit, could @WalshyDev also have a look through?
> 
> I am not enough :FeelsBadMan:

Sorry :P Just thought Walshy's experience with the guava Cache might make a difference since we've discussed how to implement this for a bit back in April and early May

2021-06-13 12:40 UTC, md5sha256 commented
👀

2021-06-20 12:08 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerCollection.java
> +final class TickerCollection {
We should annotate with @ThreadSafe

2021-06-20 12:12 UTC, WalshyDev reviewed
Looking good. Has this been stress tested?

(also apologies, didn't realise this was waiting on me)

2021-06-20 12:15 UTC, md5sha256 commented
No, it has not. I can start working on a JMH bench. I just needed an opinion on the use of the Guava Cache as I feel like I'm abusing it here.

2021-06-20 12:31 UTC, WalshyDev commented
Hmmm,Guava's Cache is made and optimised for automatic eviction (usually size or time). We don't really use any of the Cache's features at all nor use it for the intended purpose. I feel like we're better off just using ConcurrentHashMap.

The only feature/benefit we get from Cache is the weakKeys. Considering the compute and retrieval of things isn't expensive and memory is more valuable to MC servers than usual production software I think we stick to native Java ConcurrentHashMap.

2021-06-20 12:32 UTC, md5sha256 commented
Noted. So should I wrap all keys with a weak reference?

2021-06-20 12:33 UTC, WalshyDev commented
Probably best yeah

2021-06-20 12:34 UTC, md5sha256 commented
I guess I have to stick with holding the UUID instance of the world instead?

2021-06-20 12:35 UTC, WalshyDev commented
Yeah UUID would be better.

2021-06-20 12:50 UTC, md5sha256 commented
Also, by stress test do you mean a unit test that stresses the collection to check for concurrency errors or a benchmark?

2021-06-20 13:45 UTC, WalshyDev commented
> Also, by stress test do you mean a unit test that stresses the collection to check for concurrency errors or a benchmark?

Making sure it can handle concurrency correctly.

2021-06-20 14:17 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerCollection.java
> +
remove double new line

2021-06-20 14:17 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
> +
double new line

2021-06-20 15:12 UTC, md5sha256 commented
Should be good EXCEPT for https://discord.com/channels/565557184348422174/573872826327629844/856183240736899104. 
The tests currently pass as I've modified the test to not fail (I changed it to assert against a fresh `Set` from `#getBlocks` instead of `compressedPositions`. The stress test passes; however, I'm all eyes and ears for whether the stress test needs more work. 
Tested on an Intel i7-7700 (4 cores, 8 threads).

2021-06-20 15:14 UTC, md5sha256 commented
Also, I was forced to merge in `master` because I couldn't compile the new spelling tests as the localisation stuff changed. Oh well.

2021-06-26 20:03 UTC, WalshyDev requested changes

2021-06-26 20:03 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerCollection.java
> +     * Remove a location from this ticker collection.
```suggestion
     * Remove a {@link Location} from this ticker collection.
```

2021-06-26 20:03 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerCollection.java
> +     * @param location The location of the block to remove
```suggestion
     * @param location The {@link Location} of the block to remove
```

2021-06-26 20:03 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerCollection.java
> +     * @param key The world to clear the key for
```suggestion
     * Clear all the blocks for a given {@link World}
     *
     * @param key The {@link World} to remove blocks from
```

2021-06-26 20:03 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
> +     *  should be treated as <strong>read only</strong> and never exposed externally.
2 spaces at the start here
```suggestion
     * These are "Queues" of blocks that need to be removed or moved.
     * <p>
     * Whilst the {@link ConcurrentHashMap} implementation is thread-safe,
     * the {@link Location Locations} are not. Therefore, the internal copy of the locations
     * should be treated as <strong>read only</strong> and never exposed externally.
```

2021-06-26 20:03 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java
> +     * Executes all tasks in a given {@link Collection} of locations
```suggestion
     * Executes all tasks in a given {@link Collection} of {@link Location locations}
```

2021-06-26 20:10 UTC, md5sha256 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerCollection.java
> +            World world = Bukkit.getWorld(entry.getKey());
Won't that throw a concurrent modification exception, when removing keys whilst iterating over the entryset?

2021-06-26 20:11 UTC, md5sha256 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerCollection.java
> +        }
I'll PR that to cscl2 and wait for a bump.

2021-06-26 20:11 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerCollection.java
> +            World world = Bukkit.getWorld(entry.getKey());
Nope, it's thread-safe.

2021-06-26 20:16 UTC, md5sha256 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerCollection.java
> +            World world = Bukkit.getWorld(entry.getKey());
I guess, but won't that also cause the original iterator the for-loop is using to have undertiministic behaviour?

2021-06-26 20:19 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerCollection.java
> +            World world = Bukkit.getWorld(entry.getKey());
Hmmm yeah fair enough.

2021-06-26 20:56 UTC, md5sha256 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerCollection.java
> +        }
Righty then, now waiting on https://github.com/TheBusyBiscuit/CS-CoreLib2/pull/194

2021-07-03 16:20 UTC, WalshyDev approved these changes
LGTM

2021-07-03 18:31 UTC, TheBusyBiscuit approved these changes
What Walshy said 🤷🏻

2021-07-03 18:31 UTC, merged