Add a configurable step delay to the Ancient Altar
Slimefun/Slimefun4 pull request #3062
Opened 2021-05-15 09:22 UTC by martinbrom

## Description

Mass crafting rune in base Slimefun is currently very tedious. This gives the server owners the option to configure the speed themselves.

## Proposed changes

Add `IntRangeSetting` to the `AncientAltar`
Remove check for zero-tick step delay, now it is possible to craft instantly

## Related Issues (if applicable)

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-05-15 09:38 UTC, WalshyDev commented
What's the behaviour if this is 0? Also, if this was let's say 50 would there be any indication it is still doing it's thing?

2021-05-15 11:59 UTC, martinbrom commented
> What's the behaviour if this is 0?

https://youtu.be/VIfwxpv6piU

> Also, if this was let's say 50 would there be any indication it is still doing it's thing?

https://youtu.be/86PFF-uuRxY

The particles are shown 4 times (at equal intervals) per item consumed. I guess a better way to show them would be sth like once per item consumed and then once per 2 seconds, that way there wouldn't be so many when the delay is zero and so little when the delay is large. The question then would be if it's worth it and how to do it :smile:

2021-05-15 22:11 UTC, TheBusyBiscuit requested changes
The original plan was to have different tiers of altars.
This kinda ruins that of course but I can live with it for now, more configuration is always good.

2021-05-15 22:11 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientAltar.java
> +    private static final int DEFAULT_STEP_DELAY = 8;
javadocs on this would be nice.
Can also add yourself as an `@author` to this class.

2021-05-15 22:11 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientAltar.java
> +    public AncientAltar(Category category, SlimefunItemStack item, RecipeType recipeType, ItemStack[] recipe) {
Please add a "parameters are nonnull by default" annotation to this.

2021-05-15 22:11 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientAltar.java
>      }
The name "speed" here is no longer accurate.

2021-05-16 10:14 UTC, TheBusyBiscuit approved these changes
LGTM

2021-05-19 12:03 UTC, Sfiguz7 approved these changes
LGTM

2021-05-19 15:26 UTC, merged