Added EntityHitHandler
Slimefun/Slimefun4 pull request #3077
Opened 2021-05-25 01:18 UTC by Mooy1

## Description

Created the EntityHitHandler which is called when a Slimefun item is used to damage an entity. This can be used for the Blade Of Vampires, but would also be very helpful for addons, especially the one I'm creating for the Addon Jam.

## Proposed changes

Created EntityHitHandler and SlimefunItemHitListener to call the handler. Deleted VampireBladeListener and moved functionality to use the EntityHitHandler.

## Related Issues (if applicable)

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-05-25 08:32 UTC, martinbrom commented
Could you also check if the damaged entity was a player and if that hit was blocked by a shield? (in that case, probably cancel the event?)

2021-05-25 13:37 UTC, Mooy1 commented
Thats something a dev would add to their handler

2021-05-27 11:34 UTC, Sfiguz7 requested changes
Other han the changelog everything looks good to me

2021-05-27 11:34 UTC, Sfiguz7 commented on CHANGELOG.md
> +* (API) Added EntityHitHandler
Revert changes to changelog.md, these should be left for whoever compiles the new RC (cough cough Cookie)

2021-05-27 14:00 UTC, Sfiguz7 approved these changes

2021-05-27 14:04 UTC, TheBusyBiscuit requested changes

2021-05-27 14:04 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunItemHitListener.java
> +        ItemStack item = p.getInventory().getItemInMainHand();
Unnecessary empty line

```suggestion
        Player p = (Player) e.getDamager();
        ItemStack item = p.getInventory().getItemInMainHand();
```

2021-05-27 14:04 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunItemHitListener.java
> +        if (item.getType() != Material.AIR) {
Can use `Material#isAir()` here

2021-06-02 16:01 UTC, TheBusyBiscuit requested changes

2021-06-02 16:01 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SlimefunItemHitListener.java
> + * @see VampireBlade
Might make more sense to link the WeaponUseHandler here instead of the VampireBlade

2021-06-03 14:13 UTC, TheBusyBiscuit approved these changes
lgtm

2021-06-03 21:18 UTC, Sfiguz7 approved these changes

2021-06-03 21:21 UTC, merged