FlexCategories can now be made visible in CheatSheetSlimefunGuide
Slimefun/Slimefun4 pull request #3107
Opened 2021-06-06 18:41 UTC by martinbrom

## Description

Currently, it is impossible to display FlexCategories in the CheatSheetSlimefunGuide.

## Proposed changes

Add checks for `isVisible()` to both the Survival and CheatSheet books in the case of a `FlexCategory`.
A better option would probably to stop using the `isHidden()` altogether and move towards `isVisible()` since `isHidden()` is used only in one place in the whole Slimefun codebase anyway but this breaking change could introduce issues for other addons.

## Related Issues (if applicable)

No related issue, discussed for a bit in the programming-help channel.

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-06-30 17:24 UTC, Sfiguz7 approved these changes

2021-07-07 08:18 UTC, TheBusyBiscuit requested changes
I was asked to approve this.


But I will rebel :LUL:

2021-07-07 09:08 UTC, martinbrom commented
Wait, are there no changes requested O.o wat

2021-07-20 19:29 UTC, svr333 approved these changes

2021-07-26 18:57 UTC, TheBusyBiscuit approved these changes
Sorry Martin

2021-07-26 18:58 UTC, merged