Fixes #2677
Slimefun/Slimefun4 pull request #3109
Opened 2021-06-09 10:41 UTC by svr333

## Description
Fixes #2677 (all potions are treated as the same)
(Used #2831 as a basis)

## Proposed changes
Add potion meta check inside of SlimefunUtils#isItemSimilar()

## Related Issues (if applicable)
Resolves #2677

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-06-14 11:42 UTC, TheBusyBiscuit requested changes

2021-06-14 11:42 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
> +        if (checkLore) {
```suggestion
        } else if (checkLore) {
```

2021-06-25 13:15 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
> +        }
This so overly complicated, I have no idea what that is supposed to say ._.

2021-06-28 10:11 UTC, TheBusyBiscuit requested changes
Looks much more readable, do we have any unit tests for this method?
So we can ensure this wont break anything

2021-06-28 10:11 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
> +            else if (itemMeta.hasLore() != sfitemMeta.hasLore()) {
formatting

```suggestion
            } else if (itemMeta.hasLore() != sfitemMeta.hasLore()) {
```

2021-06-28 17:29 UTC, svr333 commented
I dont think we do

2021-06-28 17:32 UTC, TheBusyBiscuit commented
:monkaS: concerning

2021-07-20 09:54 UTC, TheBusyBiscuit requested changes

2021-07-20 09:54 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
> +            }
I think we should make variables here for `hasItemMetaLore` and `hasSfItemMetaLore`.

2021-07-20 19:26 UTC, svr333 commented
Do tests have to be written before this gets merged?

2021-07-25 21:59 UTC, TheBusyBiscuit approved these changes
LGTM

2021-07-26 15:27 UTC, Sfiguz7 approved these changes
LGTM too

2021-07-26 15:33 UTC, merged