Add a freeze effect on the Icy Bow (1.17)
Slimefun/Slimefun4 pull request #3127
Opened 2021-06-18 15:20 UTC by EpicPlayerA10

## Description

Add a freeze effect on the Icy Bow

## Proposed changes

Added freeze effect on 1.17 to the icy bow

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-06-18 15:23 UTC, WalshyDev requested changes

2021-06-18 15:23 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/IcyBow.java
> +                    p.setFreezeTicks(30 * 2);
nitpick
```suggestion
                if (SlimefunPlugin.getMinecraftVersion().isAtLeast(MinecraftVersion.MINECRAFT_1_17)) {
                    p.setFreezeTicks(60);
```

2021-06-19 08:30 UTC, TheBusyBiscuit approved these changes
LGTM, I think that this is a great addition

2021-06-19 08:37 UTC, WalshyDev approved these changes
LGTM

2021-06-19 08:37 UTC, merged