Fix/auto crafter empty slot check
Slimefun/Slimefun4 pull request #3155
Opened 2021-07-07 18:07 UTC by LilBC

## Description

Making auto crafters able to check and craft when there are no empty slots in the chest. I think this is a pretty important feature since it would make automation a lot easier.

## Proposed changes

A while ago I made a pull request (#3149) making the auto crafters check every slot in the chest for any non-full slot with the same item as the result of the recipe. But Biscuit said item comparisons are expensive so that would be laggy. So I'm thinking should I add a new small option in the auto crafter menu that allows the player to choose an "output slot" so only the output slot is checked every tick.

I haven't started coding this yet, so ignore the commits added to this. I just wanna make a draft first to see what people do think about this. I can start coding it if most of us think it's not a bad idea.

2021-07-07 18:17 UTC, J3fftw1 requested changes

2021-07-07 18:17 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/autocrafters/AbstractAutoCrafter.java
> +        if(inv.firstEmpty() < 0){
```suggestion
        if (inv.firstEmpty() < 0) {
```

2021-07-07 18:17 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/autocrafters/AbstractAutoCrafter.java
> +            }
```suggestion
            for (ItemStack matchingItem : inv.getContents()) {
                // Checks if any item stack that is not full that is the same type as the result.
                if (((!(resultItem instanceof SlimefunItemStack) && resultItem.isSimilar(matchingItem)) 
                || ((resultItem instanceof SlimefunItemStack) && SlimefunUtils.isItemSimilar(matchingItem, resultItem, true))) 
                && matchingItem.getAmount() < matchingItem.getMaxStackSize()
                ){
                    return true;
                }
            }
```

2021-07-07 18:42 UTC, martinbrom commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/autocrafters/AbstractAutoCrafter.java
> +import io.github.thebusybiscuit.slimefun4.utils.SlimefunUtils;
should be lower, just use the reorder imports action in your IDE (hopefully there should be one)

2021-07-07 18:45 UTC, martinbrom commented
Isn't this the exact same code that :cookie: rejected?

My previous comment about recipes that output more than 1 item is still valid, the current implementation won't start the crafting process if all of the outputs do not fit, yours would.
You'd need to do sth like this instead. There are recipes where the result amount != 1.
```
matchingItem.getAmount() + resultItem.getAmount() <= matchingItem.getMaxStackSize()
```

2021-07-07 23:01 UTC, LilBC commented
Guys no, don't mind about the code for now! XD I'm sorry if I didn't made it clear, I still haven't started coding for it yet... This PR is just proposing the idea. Ahhh... Imma remove the changes in the code.

2021-07-08 03:31 UTC, LilBC commented
I'm sorry, this PR is getting really messy and unclear. I will close it and open a new one.

2021-07-08 03:31 UTC, closed without merging