WorldBorder Support
Slimefun/Slimefun4 pull request #3196
Opened 2021-08-06 06:33 UTC by ItchyDitchy

## Description

Androids can go past and do stuff outside the world border.

## Proposed changes

Added a checker if block location is outside world border, if true, return (or do not continue)

## Related Issues (if applicable)

None

## Checklist

- [ / ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ / ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ / ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ / ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-08-06 07:26 UTC, martinbrom requested changes
Code style:

spaces, not tabs
conditions and loops always with braces

2021-08-06 07:26 UTC, martinbrom commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/FarmerAndroid.java
> +        	return;
```suggestion
        if (!block.getWorld().getWorldBorder().isInside(block.getLocation())) {
            return;
        }
```

2021-08-06 07:26 UTC, martinbrom commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/MinerAndroid.java
> +        	return;
```suggestion
        if (!block.getWorld().getWorldBorder().isInside(block.getLocation())) {
            return;
        }
```

2021-08-06 07:26 UTC, martinbrom commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/MinerAndroid.java
> +        	return;
```suggestion
        if (!block.getWorld().getWorldBorder().isInside(block.getLocation())) {
            return;
        }
```

2021-08-06 07:26 UTC, martinbrom commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/WoodcutterAndroid.java
> +        	return true;
```suggestion
        if (!target.getWorld().getWorldBorder().isInside(target.getLocation())) {
            return true;
        }
```

2021-08-06 13:41 UTC, martinbrom commented
For next time, there's a button to push all suggestions at once.

2021-08-08 12:05 UTC, svr333 requested changes

2021-08-08 12:05 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/MinerAndroid.java
> +
```suggestion

```

2021-08-08 12:05 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
> +        	    return;
tab -> spaces
```suggestion
                return;
```

2021-08-13 01:50 UTC, ItchyDitchy reviewed
Commited

2021-08-13 09:15 UTC, svr333 requested changes

2021-08-13 09:15 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/MinerAndroid.java
>              OfflinePlayer owner = Bukkit.getOfflinePlayer(UUID.fromString(BlockStorage.getLocationInfo(b.getLocation(), "owner")));
Remove trailing spaces
```suggestion

        if (!SlimefunTag.UNBREAKABLE_MATERIALS.isTagged(block.getType()) && !drops.isEmpty()) {
            OfflinePlayer owner = Bukkit.getOfflinePlayer(UUID.fromString(BlockStorage.getLocationInfo(b.getLocation(), "owner")));
```

2021-08-13 09:15 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/MinerAndroid.java
> +                if (!BlockStorage.hasBlockInfo(block)) {
Remove trailing spaces
```suggestion
                if (!BlockStorage.hasBlockInfo(block)) {
```

2021-08-13 09:15 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/MinerAndroid.java
>              OfflinePlayer owner = Bukkit.getOfflinePlayer(UUID.fromString(BlockStorage.getLocationInfo(b.getLocation(), "owner")));
Add removed line back
```suggestion

        if (!SlimefunTag.UNBREAKABLE_MATERIALS.isTagged(block.getType()) && !drops.isEmpty()) {
            OfflinePlayer owner = Bukkit.getOfflinePlayer(UUID.fromString(BlockStorage.getLocationInfo(b.getLocation(), "owner")));
```

2021-08-13 09:16 UTC, svr333 requested changes

2021-08-13 09:16 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/WoodcutterAndroid.java
> +            return true;
```suggestion

        if (!target.getWorld().getWorldBorder().isInside(target.getLocation())) {
            return true;
```

2021-08-13 09:17 UTC, svr333 approved these changes

2021-08-21 22:41 UTC, ItchyDitchy reviewed
Implemented

2021-08-30 11:43 UTC, WalshyDev approved these changes

2021-08-30 11:43 UTC, merged