Smithing table listener
Slimefun/Slimefun4 pull request #3252
Opened 2021-09-13 13:03 UTC by Sefiraat

## Description

The Smithing Table currently allows SlimefunItems to be used as the material (currently only Netherite). Given netherite is a nice looking martial for other possible items, this can allow very early access to Netherite tools unintentionally. The current examples are Zamak 1, 2 and 3 in SimpleStorage and Void Ingots in InfintyExpansion. 

## Proposed changes

New listener to deny SlimefunItems being used in the material slot. I have not modified the behavior to upgrade SlimefunItem tools from Diamond to Netherite asuming this is current both known and intended.

Tests for all 9 possible combinations of SlimefunItem, ItemStack and VanillaItem added

## Related Issues (if applicable)

Resolves https://github.com/Sefiraat/Simple-Storage/issues/8

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-09-13 13:09 UTC, WalshyDev requested changes
I'm inclined to say this should be a server option. I don't mind (and quite like) the idea of people turning SF items into netherite. It won't break (unless they're on a very old server - backwards compat).

I'm wondering what your reason for this is and what prompted this PR.

2021-09-13 13:13 UTC, Sefiraat commented
> I'm inclined to say this should be a server option. I don't mind (and quite like) the idea of people turning SF items into netherite. It won't break (unless they're on a very old server - backwards compat).
> 
> I'm wondering what your reason for this is and what prompted this PR.

I've not changed the upgrading of Slimefun Tools, this is to stop using Slimefun Items using the Netherite Ingot material being usable to upgrade any items (slimefun or vanilla). Currently Zamak-1 (very easy early game item using Netherite Ingot material) can upgade a diamond tool.

Linked issue was the trigger :)

2021-09-13 13:19 UTC, variananora commented on src/main/resources/languages/en/messages.yml
> +    not-working: '&4You cannot use a Slimefun item as a smithing material!'
spacing?

2021-09-13 13:24 UTC, WalshyDev commented
> > I'm inclined to say this should be a server option. I don't mind (and quite like) the idea of people turning SF items into netherite. It won't break (unless they're on a very old server - backwards compat).
> > I'm wondering what your reason for this is and what prompted this PR.
> 
> I've not changed the upgrading of Slimefun Tools, this is to stop using Slimefun Items using the Netherite Ingot material being usable to upgrade any items (slimefun or vanilla). Currently Zamak-1 (very easy early game item using Netherite Ingot material) can upgade a diamond tool.
> 
> Linked issue was the trigger :)

Ah yes I see. Could you make a comment above the if just indicating this is the netherite slot please.

2021-09-13 13:37 UTC, Sefiraat commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/crafting/SmithingTableListener.java
> +        if (e.getRawSlot() == 2 && e.getWhoClicked() instanceof Player && e.getInventory().getType() == InventoryType.SMITHING) {
Just removed the hanging &&

2021-09-13 13:43 UTC, Sefiraat commented
> > > I'm inclined to say this should be a server option. I don't mind (and quite like) the idea of people turning SF items into netherite. It won't break (unless they're on a very old server - backwards compat).
> > > I'm wondering what your reason for this is and what prompted this PR.
> > 
> > 
> > I've not changed the upgrading of Slimefun Tools, this is to stop using Slimefun Items using the Netherite Ingot material being usable to upgrade any items (slimefun or vanilla). Currently Zamak-1 (very easy early game item using Netherite Ingot material) can upgade a diamond tool.
> > Linked issue was the trigger :)
> 
> Ah yes I see. Could you make a comment above the if just indicating this is the netherite slot please.

Done :)

2021-09-13 22:55 UTC, WalshyDev approved these changes
LGTM

just a nitpick from the Germanism

2021-09-13 22:55 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/crafting/SmithingTableListener.java
> +            // Checks if the Item in the Material/Netherite slot is allowed to be used.
```suggestion
            // Checks if the item in the Material/Netherite slot is allowed to be used.
```

2021-09-14 08:47 UTC, svr333 requested changes
Besides the wrongly copied comment, all good

2021-09-14 08:47 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/crafting/SmithingTableListener.java
> + * cartography table.
```suggestion
 * This {@link Listener} prevents any {@link SlimefunItem} from being used in a
 * smithing table.
```

2021-09-14 09:05 UTC, Sefiraat commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/crafting/SmithingTableListener.java
> + * cartography table.
Argh! :D

2021-09-14 09:52 UTC, TheBusyBiscuit submitted a review, later dismissed
I agree with Walshy here, I also liked the fact that Slimefun tools are able to be upgraded.
There should be a check here.

Either add an option to allow usage in a smithing table and turn that on for all existing materials. This would be tedious though.

Or I would suggest making a tag with smithing materials, such as Netherite Ingots and only check those items. This way, tools can still be upgraded but custom netherite ingots cannot be used for it.

2021-09-14 10:08 UTC, Sefiraat commented
> I agree with Walshy here, I also liked the fact that Slimefun tools are able to be upgraded.
> There should be a check here.
> 
> Either add an option to allow usage in a smithing table and turn that on for all existing materials. This would be tedious though.
> 
> Or I would suggest making a tag with smithing materials, such as Netherite Ingots and only check those items. This way, tools can still be upgraded but custom netherite ingots cannot be used for it.

Hi Biscuit, This doesn't effect upgrading SF tools in anyway - it only stops using netherite ingots from incorrect sources. All slimefun tools can still be upgraded as before - both tested and one of the units tests added.

2021-09-14 10:32 UTC, svr333 approved these changes
Looks good

2021-09-14 12:37 UTC, Sefiraat commented
https://user-images.githubusercontent.com/20646323/133258699-047e8776-d643-41cd-9f65-29c7d5563d5e.mp4

Hopefully this helps show the new behavior :)

2021-09-14 12:44 UTC, J3fftw1 commented
It should throw an error in chat that you arent allowed to uss that item for upgrading

2021-09-14 12:45 UTC, WalshyDev commented
> It should throw an error in chat that you arent allowed to uss that item for upgrading

it does

2021-09-14 12:45 UTC, WalshyDev approved these changes

2021-09-14 12:46 UTC, J3fftw1 commented
> > It should throw an error in chat that you arent allowed to uss that item for upgrading
> 
> it does

Oh jeez that blended in with the background. Yea my bad

2021-09-16 17:52 UTC, Seggan commented
Does this check for `isUseableInWorkbench`? I'd really like Galactifun Tungsten Ingots (something you forgot to mention) to be used as netherite

2021-09-25 19:08 UTC, TheBusyBiscuit approved these changes
Alright, looks good to me!
Nicely done.

2021-09-25 19:15 UTC, merged