Improves item comparison performance
Slimefun/Slimefun4 pull request #3258
Opened 2021-09-15 10:30 UTC by WalshyDev

## Description
There are a lot of situations where SF items are CraftItemStacks not SlimefunItemStacks

This is most obvious with cargo and has been a big bottleneck there (~60%).

This PR addresses the cargo-specific point but will probably carry over to other parts of the code here and in addons.

In Cargo we wrap the items being used for comparison, these items can still be SF items just, they look like regular Bukkit items. So, the is item similar check should account for this.

With this change, it will check if it's wrapped and if it has item meta, if it does then it will try and get IDs to compare. Otherwise, fall back to the usual item meta comparison. This improves cargo performance by about 60% when filtering SF items.

The reason this change has such a big impact is simple, the display name code is terrible. It will decode JSON and create message components just for getting the name. It's very awkward and not nice to use. The `ItemMeta#getDisplayName` alone accounts for 60% of cargos #insert processing time in the numerous Spark reports we have received.

Call stack for this:
  - [`CargoUtils#insert`](https://github.com/Slimefun/Slimefun4/blob/7ae0128ff6aa4894d2918cf4fa184e3203f2ce45/src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java#L261-L262)
  - [`CargoUtils#matchesFilter`](https://github.com/Slimefun/Slimefun4/blob/7ae0128ff6aa4894d2918cf4fa184e3203f2ce45/src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/CargoUtils.java#L388-L393)
  - [`ItemFilter#test`](https://github.com/Slimefun/Slimefun4/blob/7ae0128ff6aa4894d2918cf4fa184e3203f2ce45/src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/cargo/ItemFilter.java#L161-L200)
  - [`SlimefunUtils#isItemSimilar`](https://github.com/Slimefun/Slimefun4/blob/7ae0128ff6aa4894d2918cf4fa184e3203f2ce45/src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java#L268-L299)

## Proposed changes
Check if an item is an `ItemStackWrapper` and try to compare IDs there too. It will only do it currently if both items are SlimefunItemStacks but that isn't the case a lot of the time.

## Related Issues (if applicable)
N/A

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

----

Requesting a review from @md5sha256 who initially introduced this wrapper code

2021-09-15 14:53 UTC, md5sha256 approved these changes
The optimisation makes a lot of sense; LGTM.

2021-09-15 18:09 UTC, Sfiguz7 approved these changes

2021-09-16 11:47 UTC, svr333 approved these changes
Looks good to me

2021-09-16 12:53 UTC, WalshyDev commented
With the help of @Sefiraat I have done some timings on a HUGE base, here are the results:

Non optimized:
```
[14:44:08 INFO]: ===== Slimefun Lag Profiler =====
[14:44:08 INFO]: Total time: 75.05ms
[14:44:08 INFO]: Running every: 0.5s (10 ticks)
[14:44:08 INFO]: Performance: :::::::::::::::::::: - Severe (75%)
[14:44:08 INFO]: 
[14:44:08 INFO]: 1434 blocks
  CARGO_NODE_INPUT - 400x (65.2ms | avg: 0.16ms)
```

Optimized:
```
[14:49:26 INFO]: ===== Slimefun Lag Profiler =====
[14:49:26 INFO]: Total time: 39.2ms
[14:49:26 INFO]: Running every: 0.5s (10 ticks)
[14:49:26 INFO]: Performance: :::::::::::::::::::: - Moderate (39%)
[14:49:26 INFO]: 
[14:49:26 INFO]: 1434 blocks
  CARGO_NODE_INPUT - 400x (30.43ms | avg: 0.08ms)
```

50% reduction!!!

2021-09-16 12:53 UTC, J3fftw1 commented
> 
> 
> With the help of @Sefiraat I have done some timings on a HUGE base, here are the results:
> 
> Non optimized:
> 
> ```
> [14:44:08 INFO]: ===== Slimefun Lag Profiler =====
> [14:44:08 INFO]: Total time: 75.05ms
> [14:44:08 INFO]: Running every: 0.5s (10 ticks)
> [14:44:08 INFO]: Performance: :::::::::::::::::::: - Severe (75%)
> [14:44:08 INFO]: 
> [14:44:08 INFO]: 1434 blocks
>   CARGO_NODE_INPUT - 400x (65.2ms | avg: 0.16ms)
> ```
> 
> Optimized:
> 
> ```
> [14:49:26 INFO]: ===== Slimefun Lag Profiler =====
> [14:49:26 INFO]: Total time: 39.2ms
> [14:49:26 INFO]: Running every: 0.5s (10 ticks)
> [14:49:26 INFO]: Performance: :::::::::::::::::::: - Moderate (39%)
> [14:49:26 INFO]: 
> [14:49:26 INFO]: 1434 blocks
>   CARGO_NODE_INPUT - 400x (30.43ms | avg: 0.08ms)
> ```
> 
> 50% reduction!!!

Not even crediting me for running these test bish

2021-09-16 12:54 UTC, Sefiraat commented
> With the help of @Sefiraat I have done some timings on a HUGE base, here are the results:
> 
> Non optimized:
> 
> ```
> [14:44:08 INFO]: ===== Slimefun Lag Profiler =====
> [14:44:08 INFO]: Total time: 75.05ms
> [14:44:08 INFO]: Running every: 0.5s (10 ticks)
> [14:44:08 INFO]: Performance: :::::::::::::::::::: - Severe (75%)
> [14:44:08 INFO]: 
> [14:44:08 INFO]: 1434 blocks
>   CARGO_NODE_INPUT - 400x (65.2ms | avg: 0.16ms)
> ```
> 
> Optimized:
> 
> ```
> [14:49:26 INFO]: ===== Slimefun Lag Profiler =====
> [14:49:26 INFO]: Total time: 39.2ms
> [14:49:26 INFO]: Running every: 0.5s (10 ticks)
> [14:49:26 INFO]: Performance: :::::::::::::::::::: - Moderate (39%)
> [14:49:26 INFO]: 
> [14:49:26 INFO]: 1434 blocks
>   CARGO_NODE_INPUT - 400x (30.43ms | avg: 0.08ms)
> ```
> 
> 50% reduction!!!

Love it.... the owners of this server will, in advance, thank you greatly for this when it's all approved xD

2021-09-16 16:12 UTC, TheBusyBiscuit approved these changes
LGTM, I will merge this on the weekend.

Also, we really should focus on writing very extensive unit tests for this method soon.
It is so widely used, yet not even remotely covered by tests.

2021-09-16 16:12 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
> +                // an ID comparison before meta comparison
Please use multiline comments the next time

2021-09-19 13:46 UTC, TheBusyBiscuit requested changes

2021-09-19 13:46 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
> +                // an ID comparison before meta comparison
multiline comment :eyes:

```suggestion
                /*
                 * Slimefun items may be ItemStackWrapper's in the context of cargo so let's try to do
                 * an ID comparison before meta comparison
                 */
```

2021-09-19 13:46 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
> +                }
Now that I have time to look at this a little closer, I spot a way we can optimize this further.
If `possibleSfItemMeta` has no id, we don't need to extract the id from `itemMeta`, reducing it by one further `ItemStack#getItemMeta()` call.

Not the prettiest but you get the idea

```suggestion
                Optional<String> possibleSfItemId = Slimefun.getItemDataService().getItemData(possibleSfItemMeta);

                if (possibleSfItemId.isPresent()) {
                    Optional<String> itemId = Slimefun.getItemDataService().getItemData(itemMeta);

                    if (itemId.isPresent()) {
                        return possibleSfItemId.get().equals(itemId.get());
                    }
                }

                return equalsItemMeta(itemMeta, possibleSfItemMeta, checkLore);
```

2021-09-19 16:57 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
> +                }
Scratch the above.
To declutter this:

We should implement a `CustomItemDataService#compare(...)` method.

2021-09-19 16:58 UTC, merged

2021-09-19 16:59 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java
> +                }
I'll make a follow-up commit.