Fixes
Slimefun/Slimefun4 pull request #3259
Opened 2021-09-15 16:18 UTC by Sfiguz7

## Description

As of now, the AutoEnchanters blindly apply whatever is on the enchanted book onto the item, disregarding any check other than compatibility ones.
A small discussion on the Discord lead to two main ideas: some people like the fact everything gets overridden, meaning an extra layer of difficulty is added as more thought and planning has to be put in instead of blindly slapping books on the item. On the other hand, some people like the idea of the enchanter not completely disregarding what is on the item to begin with, and it to be able to only update the enchantments it needs to.

This PR is motivated by this dichotomy: an additional item setting has been added that allows servers to choose whether they do want the override or not (defaulting to yes so that the old behavior is conserved). If the enchantment to be applied is of lower or equal level it is ignored meaning the enchanting time is also reduced.

## Proposed changes

Added itemSetting to AutoEnchanters to choose whether existing enchants should be overridden no matter what or checked for an improvement first. Defaults to old behavior for consistency.

## Related Issues (if applicable)

N/A

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-09-15 16:21 UTC, svr333 commented
Uh #3255

2021-09-15 16:24 UTC, Sfiguz7 commented
Ah you had done it already. Hmm I don't know if it should be a setting or just default, I don't mind either way. I will keep this open so we can choose which one to actually merge

2021-09-15 17:36 UTC, ybw0014 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java
> +import io.github.thebusybiscuit.slimefun4.api.items.ItemSetting;
this import should not be here

2021-09-16 17:54 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java
> +        // This also removes those with the same level so they aren't accounted for enchanting time
Multiline comments exist.

2021-09-16 17:58 UTC, Sfiguz7 commented
We should decide whether we want it to be optional (this PR) or permanent (#3255) before I fix the two things. Shall we have a chat in #developers?

2021-09-16 18:27 UTC, svr333 requested changes

2021-09-16 18:27 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java
> +    private final ItemSetting<Boolean> overrideExistingEnchantsLvl= new ItemSetting<>(this, "override-existing-enchants-lvl", true);
```suggestion
    private final ItemSetting<Boolean> overrideExistingEnchantsLvl= new ItemSetting<>(this, "override-existing-enchants-lvl", false);
```

2021-09-16 18:33 UTC, Sfiguz7 commented
For those with access, the discussion took place [here](https://discord.com/channels/565557184348422174/565570276038017044/888122263872872498) (just in case, for future reference)

2021-09-16 18:35 UTC, svr333 approved these changes

2021-09-19 13:34 UTC, TheBusyBiscuit approved these changes
lgtm

2021-09-19 13:34 UTC, merged