Fixes #3265
Slimefun/Slimefun4 pull request #3279
Opened 2021-09-23 11:09 UTC by variananora

## Description

You can bypass the item check by using off hand swap
Also idk where to add the comment on 'Fixes xxxx' thing

## Proposed changes

Added checks for off hand item

## Related Issues (if applicable)

Fixes #3265

## Checklist

- [X] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [X] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-09-23 11:16 UTC, WalshyDev requested changes

2021-09-23 11:16 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BackpackListener.java
> +                    }
Should this just always be cancelled? From what I can tell that isAllowed will be true still for the reported issue. Relevant code: https://github.com/Slimefun/Slimefun4/blob/eec5d2d66b2185b60c8eb34b293a9f8d78b6078a/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BackpackListener.java#L121-L127

```suggestion
                } else if (e.getClick() == ClickType.SWAP_OFFHAND && e.getClickedInventory().getType() != InventoryType.PLAYER) {
                    // Fixes #3265
                    ItemStack offHandItem = e.getWhoClicked().getInventory().getItemInOffHand();

                    if (!isAllowed((SlimefunBackpack) backpack, offHandItem)) {
                        e.setCancelled(true);
                    }
```

2021-09-23 11:22 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BackpackListener.java
> +                    }
Oh wait I see, the item will be the backpack which isn't allowed. Me dumb

2021-09-28 12:30 UTC, svr333 approved these changes
LGTM

2021-09-28 14:10 UTC, WalshyDev approved these changes

2021-09-28 14:13 UTC, merged