Implement Multimeter Functionality on Generators
Slimefun/Slimefun4 pull request #3300
Opened 2021-10-04 09:46 UTC by md5sha256

## Description

Implementation of #2314

## Proposed changes

Add a new method `EnergyNetProvider#peekGeneratedEnergy`
Add a new message `messages.multimeter-generating`

## Related Issues (if applicable)

Resolves #2314

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-10-04 10:07 UTC, WalshyDev requested changes

2021-10-04 10:07 UTC, WalshyDev commented on src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AGenerator.java
> +    }
This method is overly long. Can we clean this up a bit?

2021-10-04 10:07 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/reactors/Reactor.java
> +    private int peekGenerateEnergy(@Nonnull Location l, @Nonnull Config data, @Nonnull BlockMenu inv, @Nullable BlockMenu accessPort, FuelOperation operation) {
Can we extract some of the dupe code here? There's no reason to do a bunch of this in both peekGenerateEnergy and generateEnergy

2021-10-04 10:07 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/generators/SolarGenerator.java
> +        // Solar panels will not change when generating energy
```suggestion
        // Solar panels do not consume fuel, we can fallback to the original method
```

2021-10-04 10:07 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/Multimeter.java
> +                            Slimefun.getLocalization().sendMessage(p, "messages.multimeter", false, str -> str.replace("%stored%", stored).replace("%capacity%", capacity));
I'd prefer moving multimeter out of messages now that it has multiple messages.

2021-10-04 10:07 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/Multimeter.java
> +import io.github.thebusybiscuit.slimefun4.core.attributes.EnergyNetProvider;
Import belongs with the others

2021-10-04 10:07 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/EnergyNetProvider.java
> +     * consume any fuel or modify the provider in any way.
English here can be improved.
```suggestion
     * This method will return how much this {@link EnergyNetProvider} is expected to provide to the {@link EnergyNet}.
     * It is not to be confused with {@link #getGeneratedOutput(Location, Config)}.
     * This method <b>should not</b> consume any fuel or modify the provider in any way.
```

2021-10-04 10:07 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/EnergyNetProvider.java
> +     * @param l
new line
```suggestion
     *
     * @param l
```

2021-10-04 17:23 UTC, TheBusyBiscuit requested changes
I am not a fan of this approach.
Adding this new method will over-complicate the energy generator implementations unnecessarily.
I don't see this feature as a justifiable reason for this over-complication.

I reckon it would be much less intrusive to have Energy networks simply keep a cache of generated energy amounts per generator which is re-populated on each cycle.
The Multimeter could then just read from the current cache.

2021-11-20 18:18 UTC, TheBusyBiscuit commented
Is this still being worked on or can it be considered stale?

2021-11-20 18:26 UTC, md5sha256 commented
Can be considered stale. Havent had the time to work on it.

2021-11-20 18:26 UTC, closed without merging