Added Talisman of the Farmer (approved suggestion)
Slimefun/Slimefun4 pull request #3305
Opened 2021-10-05 22:25 UTC by Sfiguz7

## Description

From 1.16 fortune can be applied (and works) on hoes too. It only makes sense for a crops related counterpart of the Miner Talisman (chance to dupe ore drops) to exist in Slimefun to reflect this addition.
The addition was suggested on Discord and has been approved on August 8th, 2021 (suggestion \#1473)
## Proposed changes

- Added a Talisman of the Farmer
- Added a research for the Talisman of the Farmer
- Added to the TalismanListener BlockBreakEvent to reflect the change
- Added a new SlimefunTag for the Talisman triggers (same as Crop Growth Accellerator minus the pumpkin and melon stems

## Related Issues (if applicable)

Suggestion \#1473 on the Discord (approved on August 8th, 2021)
## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-10-06 18:59 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
> +            // We also want to double crops
comment could be clearer
```suggestion
            // Handle double drops for Farmer Talisman
```

2021-10-06 18:59 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
> +                    // Fixes #2077
comment is about miner talisman

2021-10-06 18:59 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
> +                        // Fixes #2818
comment is about miner talisman

2021-10-06 20:16 UTC, svr333 commented
you renmoved the comments on the miner talisman not on the farmer talisman

2021-12-20 11:29 UTC, TheBusyBiscuit requested changes
Took me long enough to get to this.
Looks simple but I feel like this is way too redundant

2021-12-20 11:29 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
> +            }
This is all almost identical with the Miner Talisman code above.
To combat this redundancy, you could create a `doubleDrops` method with parameters here

2021-12-20 12:39 UTC, TheBusyBiscuit approved these changes
That looks much more organized!

2021-12-20 12:41 UTC, TheBusyBiscuit requested changes

2021-12-20 12:41 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TalismanListener.java
> +import io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem;
unused import

2021-12-20 13:36 UTC, TheBusyBiscuit approved these changes

2021-12-20 15:57 UTC, svr333 approved these changes

2021-12-21 09:42 UTC, merged