Re-adding gravity_affected_blocks.json and adding "GRAVITY_AFFECTED_BLOC…
Slimefun/Slimefun4 pull request #3315
Opened 2021-10-10 11:09 UTC by TerslenK

…KS" into SlimefunTag.java

## Description
i made this pull request before, but i made some issues so this pull request should fix them

## Proposed changes
added src/main/resources/tags/gravity_affected_blocks.json
added "GRAVITY_AFFECTED_BLOCKS" into src/main/java/io/github/thebusybiscuit/slimefun4/utils/tags/SlimefunTag.java

## Related Issues (if applicable)

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2021-10-10 11:11 UTC, TerslenK commented
im sure i made everything correct rn

2021-10-10 11:11 UTC, WalshyDev commented
Why did you open a new PR rather than just committing to the old one?

2021-10-10 11:13 UTC, TerslenK commented
> You just... Commit more

eeh

sorry i guess ¯\_(ツ)_/¯

2021-10-10 11:15 UTC, TerslenK commented
> Just a small typo, everything else seems fine to me

sorry i dont have a good grammar

2021-10-10 11:28 UTC, WalshyDev commented
Is there not a tag for concrete powder?

also I believe most of the tags have unit tests. If so, we should have one here too

2021-10-10 12:48 UTC, WalshyDev submitted a review, later dismissed

2021-11-01 13:10 UTC, J3fftw1 requested changes

2021-11-01 13:10 UTC, J3fftw1 commented on src/main/resources/tags/gravity_affected_blocks.json
> +		"minecraft:damaged_anvil",
```suggestion
		#minecraft:anvil,
```

2021-11-01 14:49 UTC, J3fftw1 commented on src/main/resources/tags/gravity_affected_blocks.json
> +        "#minecraft:anvil",
move anvil above slimefun tag

2021-11-01 14:50 UTC, TerslenK commented on src/main/resources/tags/gravity_affected_blocks.json
> +        "#minecraft:anvil",
okay

2021-11-01 14:57 UTC, TerslenK commented on src/main/resources/tags/gravity_affected_blocks.json
> +        "#minecraft:anvil",
is it right now?

2021-11-01 15:09 UTC, variananora approved these changes
LGTM

2021-11-01 15:12 UTC, svr333 approved these changes
LGTM

2021-11-30 21:10 UTC, TheBusyBiscuit approved these changes
LGTM

2021-12-06 15:34 UTC, Sfiguz7 approved these changes

2021-12-10 18:00 UTC, TheBusyBiscuit approved these changes
Why hasn't this been merged yet?

2021-12-10 18:01 UTC, merged

2021-12-10 18:57 UTC, svr333 commented
wasnt merged because no one can but walshy and he didnt check it

2021-12-10 19:01 UTC, TerslenK commented
finally 😅