Fix/fix light block issue
Slimefun/Slimefun4 pull request #3489
Opened 2022-03-11 07:28 UTC by Silent-Program

## Description

When placing cargo node on chest while light block is present it tells the player you may not do so.
## Proposed changes

Allow players to place cargo nodes inside of light blocks (you can place vanilla blocks inside of light blocks)
## Related Issues (if applicable)

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2022-03-11 07:29 UTC, Silent-Program commented
This is the second PR as I put the check in the wrong place and bonked up the on top of the chest check.  But I double-checked that that is no longer broken and indeed it is not.

2022-03-11 09:11 UTC, variananora reviewed
I advise you to see our code standards here: https://github.com/Slimefun/Slimefun4/blob/master/CONTRIBUTING.md

2022-03-11 09:11 UTC, variananora commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/CargoNodeListener.java
> +import javax.annotation.Nonnull;
import order

2022-03-11 09:13 UTC, variananora requested changes

2022-03-11 09:13 UTC, variananora commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/CargoNodeListener.java
> +	}
use spaces, not tabs

2022-03-11 09:13 UTC, variananora commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/CargoNodeListener.java
> +			if (e.getBlockReplacedState().getType() == Material.LIGHT) return;
use brackets

2022-03-11 09:19 UTC, Sefiraat commented
Wont this still allow placing above or below a block? I may be screwing up the logic and I cant test personally but it looks like a light block above/below a block will then allow a cargo node to be placed in a location where it shouldn't be.

2022-07-09 18:54 UTC, TheBusyBiscuit commented
Closing this as stale

2022-07-09 18:54 UTC, closed without merging