Fix industrial miner mining up sf blocks
Slimefun/Slimefun4 pull request #3529
Opened 2022-04-12 07:04 UTC by FN-FAL113

## Description
Prevent the industrial miner from mining any sf blocks that uses ores as their material

## Proposed changes
- Added a short circuit condition to prevent unintentional mining of sf blocks

## Related Issues (if applicable)

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2022-04-12 09:46 UTC, FN-FAL113 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/MiningTask.java
> +                    if (!BlockStorage.hasBlockInfo(b) && miner.canMine(b.getType()) && push(miner.getOutcome(b.getType()))) {
I shall move it when I get into my pc, It seems like i I shouls have put it in there last time I checked it my logic wasn't able to reach it and focused on the task conditions

2022-04-19 18:17 UTC, TheBusyBiscuit requested changes

2022-04-19 18:17 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java
> +            return SlimefunTag.INDUSTRIAL_MINER_ORES.isTagged(block.getType()) && BlockStorage.check(block) == null;
You can use `BlockStorage#hasBlockInfo()` instead here.

2022-04-21 01:44 UTC, FN-FAL113 commented
Bump

2022-04-29 11:34 UTC, TheBusyBiscuit requested changes

2022-04-29 11:34 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java
> +            return SlimefunTag.INDUSTRIAL_MINER_ORES.isTagged(block.getType()) && BlockStorage.hasBlockInfo(block);
Shouldn't these be inverted?
The block should only be mineable if it has **NO** blockinfo.

2022-06-16 13:34 UTC, FN-FAL113 commented
woah didn't know this pr is 2 months old now

2022-08-04 09:25 UTC, FN-FAL113 commented
Re-opening this, since there are no guys who are willing to make a pr for the issue. This might be in need of review, my little time can still manage this after dealing with some stuffs irl

2022-08-04 09:31 UTC, FN-FAL113 commented
if in need of change, Will have to do another pr with a new branch since this pr's fork is removed

2022-08-04 23:50 UTC, Phoenix-Starlight commented
Can't you restore the branch?

2022-08-05 01:06 UTC, closed without merging