Fix Arithmetic Error
Slimefun/Slimefun4 pull request #3541
Opened 2022-04-20 21:45 UTC by itslukemango

## Description

We found this issue by accident, but it seems that if Slimefun's ticks are faster than expected, Tier 3 items such as Electric Ore Grinders will produce an ArithmeticException.

https://pastebin.com/ZGWDJyWn - the error from our fork, this small patch fixed it.

## Proposed changes

Don't update the progress bar if the operation is already finished

## Related Issues (if applicable)

Resolves #3538

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2022-04-20 21:48 UTC, Sfiguz7 submitted a review, later dismissed
It's likely Biscuit will want the update progress to be in an else block but I personally don't mind it. I will just approve and let him or Walshy decide if they want to suggest the change before merging

2022-04-20 21:56 UTC, itslukemango commented
yeah I mean I don't mind changing it if that's what's preferred :)

2022-04-21 08:46 UTC, svr333 approved these changes

2022-04-22 08:35 UTC, TheBusyBiscuit requested changes
I approve of this, I even checked the logic and made a truth table.
But as pointed out, style-wise an inclusive-if would be preferred and we generally like to keep a reference to the fixed issue so we can better track these things.

Otherwise, it looks good! Thanks!

2022-04-22 08:35 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/machines/MachineProcessor.java
>          ChestMenuUtils.updateProgressbar(inv, slot, remainingTicks, totalTicks, getProgressBar());
```suggestion
        // Fixes #3538 - If the operation is finished, we don't need to update the progress bar.
        if (remainingTicks > 0 || totalTicks > 0) {
            ChestMenuUtils.updateProgressbar(inv, slot, remainingTicks, totalTicks, getProgressBar());
        }
```

2022-04-23 09:57 UTC, Sfiguz7 approved these changes
LGTM

2022-04-23 11:18 UTC, TheBusyBiscuit approved these changes

2022-04-23 11:19 UTC, svr333 approved these changes

2022-04-23 11:20 UTC, merged