Added Seagrass recipe (suggestion #398 from Mr.Moules)
Slimefun/Slimefun4 pull request #3546
Opened 2022-04-22 13:26 UTC by craftish37

## Description

Simple add of an item following player suggestion
## Proposed changes

Adding Seagrass organic food, crafted with the Food Fabricator
## Related Issues (if applicable)

--- No Issues related ---
## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

## Anything else
This is a speedly-made PR, I didn't searched that much where this add could break so feel free to notice me 👌

2022-04-22 13:28 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FoodFabricator.java
> +        registerRecipe(12, new ItemStack[] { SlimefunItems.TIN_CAN, new ItemStack(Material.SEAGRASS) }, new ItemStack[] { new SlimefunItemStack(SlimefunItems.SEAGRASS_ORGANIC_FOOD, OrganicFood.OUTPUT
When was sea grass added?

2022-04-22 13:30 UTC, Sefiraat commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FoodFabricator.java
> +        registerRecipe(12, new ItemStack[] { SlimefunItems.TIN_CAN, new ItemStack(Material.SEAGRASS) }, new ItemStack[] { new SlimefunItemStack(SlimefunItems.SEAGRASS_ORGANIC_FOOD, OrganicFood.OUTPUT
1.13

2022-04-22 13:36 UTC, craftish37 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FoodFabricator.java
> +        registerRecipe(12, new ItemStack[] { SlimefunItems.TIN_CAN, new ItemStack(Material.SEAGRASS) }, new ItemStack[] { new SlimefunItemStack(SlimefunItems.SEAGRASS_ORGANIC_FOOD, OrganicFood.OUTPUT
In terms of version ? 1.13.x

2022-04-22 13:42 UTC, Sefiraat requested changes

2022-04-22 13:42 UTC, Sefiraat commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FoodFabricator.java
> +        registerRecipe(12, new ItemStack[] { SlimefunItems.TIN_CAN, new ItemStack(Material.SEAGRASS) }, new ItemStack[] { new SlimefunItemStack(SlimefunItems.SEAGRASS_ORGANIC_FOOD, OrganicFood.OUTPUT
The SlimefunItemStack you reference here `SEAGRASS_ORGANIC_FOOD` doesn't exist. This is making the build fail

2022-04-22 14:07 UTC, Sefiraat commented
Lovely looks like it’s building so that’s good! 

You’ve not ticked that you have tested this change so I can’t approve it until you do. Please build locally and ensure it’s all working as expected if you could :)

2022-04-22 14:17 UTC, variananora commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/SlimefunItemSetup.java
> +    new OrganicFertilizer(itemGroups.misc, SlimefunItems.SEAGRASS_FERTILIZER, SlimefunItems.SEAGRASS_ORGANIC_FOOD)
```suggestion
        new OrganicFertilizer(itemGroups.misc, SlimefunItems.SEAGRASS_FERTILIZER, SlimefunItems.SEAGRASS_ORGANIC_FOOD)
```
formatting

2022-04-22 15:59 UTC, craftish37 commented
Seems pretty good for now, any formatting/ other requests ? 🙂

2022-04-23 01:50 UTC, variananora approved these changes
LGTM

2022-04-23 11:16 UTC, TheBusyBiscuit approved these changes
LGTM

2022-04-23 11:25 UTC, svr333 approved these changes

2022-04-23 11:27 UTC, TheBusyBiscuit commented
We need ALL the reviews here apparently :eyes:

2022-04-23 11:28 UTC, svr333 commented
yeah, this PR is world altering I thought Id give my much needed approval

2022-04-23 11:36 UTC, FN-FAL113 commented
thats a lot of assignees dope

2022-04-23 11:40 UTC, craftish37 commented
That’s a lotta people for some watery grass pieces 🤣

2022-04-23 20:56 UTC, Sefiraat approved these changes
Ok, I have 69 required urgent changed before this can go live. Lol jk, LTGM

2022-04-24 13:12 UTC, craftish37 commented
Needs anything else to merge ?

2022-04-24 14:07 UTC, Sefiraat commented
> Needs anything else to merge ?

Nope! Just gotta wait for cookie or walshy to merge now

2022-04-24 17:26 UTC, merged