Replace Validate checks
Slimefun/Slimefun4 pull request #3589
Opened 2022-06-11 21:39 UTC by ybw0014

## Description

As #3586 said, replace all Validate checks with Precondition.

## Proposed changes

## Related Issues (if applicable)

Resolves #3586

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2022-06-11 22:33 UTC, ybw0014 commented
Not sure about how you would like to replace `Validate.noNullElements`, so discuss it here or https://discord.com/channels/565557184348422174/565570276038017044/985310097955758081.

2022-06-11 23:16 UTC, WalshyDev requested changes

2022-06-11 23:16 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java
> +            Preconditions.checkArgument(handler != null, "You cannot add any 'null' ItemHandler!");
This should definitely be a util method.

I don't think it warrants needing to be in dough so I'd just add it under our utils package.

2022-06-14 10:37 UTC, TheBusyBiscuit requested changes
I really find `Preconditions.checkNotNull` better semantic wise but it's a shame that it throws an NPE...

I was really hoping we could avoid writing our own util for it, but it really seems like `Preconditions` doesn't cover our use cases too well...

Perhaps a `Validate` class should be added to `dough-common` then... or Slimefun's util package.
What do the others think?

2022-06-14 11:42 UTC, J3fftw1 commented
> I really find `Preconditions.checkNotNull` better semantic wise but it's a shame that it throws an NPE...
> 
> I was really hoping we could avoid writing our own util for it, but it really seems like `Preconditions` doesn't cover our use cases too well...
> 
> Perhaps a `Validate` class should be added to `dough-common` then... or Slimefun's util package. What do the others think?

I would say push this to Dough so plugins that use Dough only and not Slimefun can make use of it aswell.

2022-06-29 19:47 UTC, ybw0014 commented
I'll open a new pr when https://github.com/baked-libs/dough/pull/184 is merged.

2022-06-29 19:47 UTC, closed without merging