Added Glow Berries Being Useful
Slimefun/Slimefun4 pull request #3594
Opened 2022-06-17 20:37 UTC by TheWireLord

## Description

Adding usability to the Glow Berries which were added in the 1.17 update.
## Proposed changes

+ Added Glow Berry Juice as a result of using Glow Berries in the Juicer. (With the same stats as Sweet Berry Juice)
+ Added Glow Berries as a fuel in the Bio Reactor. (With the same stats as Sweet Berries).
+ Updated Wiki to include Glow Berry Juice.
## Related Issues (if applicable)

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2022-06-18 14:40 UTC, TheBusyBiscuit approved these changes
Pretty much looking good to me, thank you!

Although a part of me wished glow berry juice gave night vision XD

2022-06-18 14:59 UTC, Sefiraat commented
> Pretty much looking good to me, thank you!
> 
> Although a part of me wished glow berry juice gave night vision XD

I was going to say it should, surely, give the glowing effect :D?

2022-06-18 15:02 UTC, Sefiraat approved these changes
Looking fine, though swapping out for Night Vision or Glowing would make far more sense given the item, imo

2022-06-18 15:53 UTC, TheWireLord commented
> Pretty much looking good to me, thank you!
> 
> Although a part of me wished glow berry juice gave night vision XD

I had also thought of this, but it looked like the suggestion was not super popular in the Suggestions channel in Discord.
I feel that the Night Vision may be too much and may replace the potion, but I could see the Glowing effect be a possibility. I'm going to look into that.

2022-06-27 13:32 UTC, Sefiraat commented
Personally I am in favour of what @Sfiguz7 mentioned on Discord, changing/overloading the SlimefunItemStack constructor to allow for multiple PotionEffects. Then perhaps all give a basic level of saturation and then specific ones could give additional effects based on their theme. However to avoid scope slipping, perhaps just make this one `GLOWING` for the time being and then it could be expanded on in a future PR?

2022-09-29 11:36 UTC, TheBusyBiscuit requested changes

2022-09-29 11:36 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/generators/BioGenerator.java
> +        registerFuel(new MachineFuel(2, new ItemStack(Material.GLOW_BERRIES)));
These are already added below (being the version check)

```suggestion
```

2022-09-29 15:58 UTC, TheBusyBiscuit approved these changes

2022-09-29 15:59 UTC, merged