Multimeter additional info
Slimefun/Slimefun4 pull request #3616
Opened 2022-07-12 13:52 UTC by Sefiraat

## Description
This isn't directly for Slimefun. Many addons have blocks that display information about their current operational status within a GUI inventory. While this is a good way to do this from the player's perspective, this creates a BlockMenu that is kept in RAM indefinitely which has recently been the cause of some issues. While the block storage rewrite will likely be the best 'fix' for this, for now this is to allow addons to remove information-only GUIs for their machines.

The biggest 'offender' for this is InfinityExpansion which in my most recent example server had 70k~ of these inventories which are, effectively, wasting RAM - and a lot of it.
If accepted I will be using this in Infinity, Networks and Tinker and will recommend to any other addons with similar blocks.

This solution will allow addons to display the information they are trying to put forward through the MultiMeter

## Proposed changes
Add a new ItemAttribute that addons can implement to add additional messages to the MultiMeter.

This could easily be a new tool instead. While I think it fits well in the MultiMeter, I'm happy to make a new item for this purpose.

## Related Issues (if applicable)

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.14.* - 1.19.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2022-07-12 14:49 UTC, TheBusyBiscuit requested changes
This feels like unnecessary weight in my opinion.
Why not add a default method to `EnergyComponent` like `sendMultimeterInfo(Player player, Location location)`, move the stuff for the default message there and override if necessary?

Sure, then every item would need to be required to be an energy component for the multimeter to be able to read it. But then again, a multimeter working on something that is not an energy component seems un-intuitive anyway.

2022-07-12 15:01 UTC, Sefiraat commented
> This feels like unnecessary weight in my opinion. Why not add a default method to `EnergyComponent` like `sendMultimeterInfo(Player player, Location location)`, move the stuff for the default message there and override if necessary?
> 
> Sure, then every item would need to be required to be an energy component for the multimeter to be able to read it. But then again, a multimeter working on something that is not an energy component seems un-intuitive anyway.

I did have two non-energycomponent items in my scope. Would a new item called a Probe be accepted instead? If not ill do as you suggest as near all the weight in the blockstorage reports I've worked on are EnergyComponents and should be enough in the main

2022-08-06 12:58 UTC, svr333 submitted a review, later dismissed
I like the simplicity of this implementation, I think it'll suffice for addon usage atm

2022-08-08 12:28 UTC, TheBusyBiscuit requested changes

2022-08-08 12:28 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/Multimeter.java
> +                    component.sendMultimeterInfo(p, l);
Maybe extract this into the default method:
`Slimefun.getLocalization().sendMessage(p, "messages.multimeter", false, str -> str.replace("%stored%", stored).replace("%capacity%", capacity));`

```suggestion
                    component.sendMultimeterInfo(p, l);
                    p.sendMessage("");
```

This way the padding is kept consistently and it allows you to specify whether your extra info should be added above or below the default text.

2022-08-08 12:28 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/EnergyNetComponent.java
> +     * {@link io.github.thebusybiscuit.slimefun4.implementation.items.electric.gadgets.Multimeter} is used.
Why is this written out...?
Add an import instead, you use the short version below anyway.
```suggestion
     * {@link Multimeter} is used.
```

2023-03-07 15:41 UTC, Sfiguz7 submitted a review, later dismissed
LGTM, it is actually a good idea to move off of GUIs. It does make it slightly more inconvenient for players but the advantage in terms of server resources outweighs that imo

2023-03-08 21:05 UTC, svr333 submitted a review, later dismissed

2023-06-11 00:30 UTC, WalshyDev reviewed
LGTM just quick english fix + nit :)

2023-06-11 00:30 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/EnergyNetComponent.java
> +     * Override this method to change what information shown to the {@link Player} when a
```suggestion
     * Override this method to change what information is shown to the {@link Player} when a
```

2023-06-11 00:30 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/gadgets/Multimeter.java
> +                    e.cancel();
nit: I'd put this at the start/start of the if, bit weird to have this in the middle (and easy to get lost -- "is this cancelled?" - not quick to find when surrounded by code)

2023-08-03 11:18 UTC, J3fftw1 commented
marked this as stale no activity in almost 2 months.
Will close this after a week, if its still stale.

2023-09-16 21:55 UTC, closed without merging