Making range not hardcoded
Slimefun/Slimefun4 pull request #3642
Opened 2022-08-05 15:46 UTC by TerslenK

## Description
i just pred wrong branch

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.14.* - 1.19.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2022-08-05 15:46 UTC, TerslenK commented
first one important, others are blank

2022-08-06 11:17 UTC, WalshyDev requested changes
Doesn't feel like this should be on EnergyNetComponent, I'm not sure how that'd work exactly.

Why isn't this in EnergyNet or Network or EnergyConnector?

What is the thing which has a range right now?

Regardless, here's my review

2022-08-06 11:17 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/EnergyNetComponent.java
> +
```suggestion
```

2022-08-06 11:17 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java
> +        return EnergyNetComponent.getRange();
you're trying to access this staticly, how is that supposed to work if it can change per component? 🤔

2022-08-06 11:17 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/EnergyConnector.java
> +    private final int RANGE;
```suggestion
    private final int RANGE;

```

2022-08-06 11:17 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/EnergyConnector.java
> +    @ParametersAreNonnullByDefault
```suggestion

    @ParametersAreNonnullByDefault
```

2022-08-06 11:17 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/EnergyConnector.java
> +        this.RANGE = 6;
just call the other constructor
```suggestion
        this(itemGroup, item, recipeType, recipe, recipeOutput, 6);
```

2022-08-06 11:17 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/EnergyConnector.java
> +
```suggestion
```

2022-08-06 11:17 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/EnergyConnector.java
> +
```suggestion
@Override
```

2022-08-06 11:17 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/utils/LoreBuilder.java
> +        else {
```suggestion
        } else {
```

2022-08-16 08:47 UTC, closed without merging