Add Basalt->Blackstone recipe
Slimefun/Slimefun4 pull request #3679
Opened 2022-10-01 16:52 UTC by svr333

## Description
Adds a new recipe to convert 2 basalt into one blackstone (useful for nether only players)

## Proposed changes
New recipe to the grindstone

## Related Issues (if applicable)
[Discord suggestion 2007](https://discord.com/channels/565557184348422174/627048923122499584/993741632878940260)

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.14.* - 1.19.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2022-10-04 08:44 UTC, TheBusyBiscuit requested changes

2022-10-04 08:44 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
> +        recipes.add(new ItemStack(Material.BLACKSTONE));
Those are 1.16+ only items aren't they?

2022-10-04 09:23 UTC, svr333 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
> +        recipes.add(new ItemStack(Material.BLACKSTONE));
oh yeah, my bad

2022-10-17 15:16 UTC, TheBusyBiscuit submitted a review, later dismissed
lgtm

2023-01-31 02:01 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
> +        if (Slimefun.getMinecraftVersion().isAtLeast(MinecraftVersion.MINECRAFT_1_16)) {
Version check no longer required 😅 

```suggestion
        if (Slimefun.getMinecraftVersion().isAtLeast(MinecraftVersion.MINECRAFT_1_16)) {
```

2023-03-04 10:22 UTC, Sefiraat approved these changes
👍

2023-03-07 15:37 UTC, Sfiguz7 approved these changes
LGTM

2023-03-07 21:54 UTC, TheBusyBiscuit approved these changes

2023-03-07 21:57 UTC, merged