Feature/sound
Slimefun/Slimefun4 pull request #3694
Opened 2022-10-15 13:26 UTC by J3fftw1

## Description

Merged all commits from master
Updated some minor things that java 16 added
Please squash this pr because of all those commits

## Proposed changes

This PR will add more sounds from the sound manager

## Related Issues (if applicable)

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.14.* - 1.19.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2022-10-16 16:56 UTC, svr333 commented
![image](https://user-images.githubusercontent.com/35664724/196048047-c79c0264-d852-4549-92e6-f464fe9ae796.png)
😅

2022-10-16 16:58 UTC, J3fftw1 commented
> ![image](https://user-images.githubusercontent.com/35664724/196048047-c79c0264-d852-4549-92e6-f464fe9ae796.png) 😅

Have fun XD
Everything before the last few is just master tho

2022-10-16 20:42 UTC, svr333 commented
oh okay thats doable then, hope I can filter that out somehow

2022-10-16 20:43 UTC, J3fftw1 commented
Just check commits instead of file changes

2022-10-16 20:45 UTC, svr333 commented
fair, I also found this though, you can select x commits to view, but its too laggy with the 300 files open and stuff
![image](https://user-images.githubusercontent.com/35664724/196057432-b2ff8321-7683-45d1-8de9-1634de53b538.png)

2022-10-17 08:14 UTC, J3fftw1 commented
apparently the unit tests should work.
I messed something up somewhere cant find where exactly
Dont merge yet
Reviews are welcome tho

2022-10-17 10:49 UTC, TheBusyBiscuit requested changes
A ton of formatting issues, I eventually gave up pointing them out. And lots of unnecessary field member creations

2022-10-17 10:49 UTC, TheBusyBiscuit commented on pom.xml
> +            <version>2.29.0</version>
No.

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/options/SlimefunGuideSettings.java
> +        menu.addMenuOpeningHandler(SoundEffect.GUIDE_BUTTON_CLICK_SOUND::playFor);
These are two completely different sounds...

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/options/PlayerLanguageOption.java
> +        menu.addMenuOpeningHandler(SoundEffect.GUIDE_BUTTON_CLICK_SOUND::playFor);
These are two completely different sounds...

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/options/ContributorsMenu.java
> +        menu.addMenuOpeningHandler(SoundEffect.GUIDE_BUTTON_CLICK_SOUND::playFor);
These are two completely different sounds...

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/LongFallBoots.java
> +import io.github.thebusybiscuit.slimefun4.core.services.sounds.SoundEffect;
double import

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/backpacks/EnderBackpack.java
>      public ItemUseHandler getItemHandler() {
formatting
```suggestion
    @Override
    public @Nonnull ItemUseHandler getItemHandler() {
```

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/entities/IronGolemAssembler.java
> +import io.github.thebusybiscuit.slimefun4.core.services.sounds.SoundEffect;
duplicate import

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/food/DietCookie.java
>      public ItemConsumptionHandler getItemHandler() {
formatting. Also not even relevant to the sound manager PR
```suggestion
    @Override
    public @Nonnull ItemConsumptionHandler getItemHandler() {
```

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/food/MagicSugar.java
>      public ItemUseHandler getItemHandler() {
formatting...
```suggestion
    @Override
    public @Nonnull ItemUseHandler getItemHandler() {
```

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/InfusedHopper.java
>      public BlockTicker getItemHandler() {
formatting
```suggestion
    @Override
    public @Nonnull BlockTicker getItemHandler() {
```

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/KnowledgeFlask.java
>      public ItemUseHandler getItemHandler() {
formatting
```suggestion
    @Override
    public @Nonnull ItemUseHandler getItemHandler() {
```

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/KnowledgeTome.java
>      public ItemUseHandler getItemHandler() {
formatting
```suggestion
    @Override
    public @Nonnull ItemUseHandler getItemHandler() {
```

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicEyeOfEnder.java
>      public ItemUseHandler getItemHandler() {
formatting
```suggestion
    @Override
    public @Nonnull ItemUseHandler getItemHandler() {
```

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicalZombiePills.java
>      public EntityInteractHandler getItemHandler() {
formatting...
```suggestion
    @Override
    public @Nonnull EntityInteractHandler getItemHandler() {
```

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/runes/SoulboundRune.java
>      public ItemDropHandler getItemHandler() {
formatting
```suggestion
    @Override
    public @Nonnull ItemDropHandler getItemHandler() {
```

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestSmithingTableListener.java
> +    private static Slimefun plugin;
Just why...

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestFireworksListener.java
> +    private static Slimefun plugin;
Just why...

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestCoolerListener.java
> +    private static Slimefun plugin;
Just why...

2022-10-17 10:49 UTC, TheBusyBiscuit commented on src/test/java/io/github/thebusybiscuit/slimefun4/core/commands/TestResearchCommand.java
> +    private static Slimefun plugin;
Just why...

2022-11-03 09:46 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/weapons/VampireBlade.java
> +import io.github.thebusybiscuit.slimefun4.core.services.sounds.SoundEffect;
duplicate import

2022-11-03 09:47 UTC, TheBusyBiscuit commented on src/test/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/TestFireworksListener.java
> +    private static Slimefun plugin;
unused field

2023-05-22 07:41 UTC, J3fftw1 commented
Could this be reviewed and the branch this is building against being updated?

2023-06-12 17:55 UTC, J3fftw1 commented
What needs to be unit tested on this pr?

2023-06-14 02:05 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java
> +                    }
*I wish this could be a ternary*

2023-06-14 15:45 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java
> +                    }
yea same

2023-06-14 17:18 UTC, JustAHuman-xD requested changes

2023-06-14 17:18 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundEffect.java
>      BEE_BOOTS_FALL_SOUND("block.honey_block.fall", 1F, 1F),
This can be replaced with the correspond enum

2023-06-14 17:18 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundEffect.java
>      IRON_GOLEM_ASSEMBLER_ASSEMBLE_SOUND("entity.iron_golem.repair", 0.5F, 1F),
This can be replaced with the corresponding enum

2023-06-14 18:58 UTC, JustAHuman-xD requested changes

2023-06-14 18:58 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/medical/Vitamins.java
> +import io.github.thebusybiscuit.slimefun4.core.services.sounds.SoundEffect;
Duplicate import

2023-06-14 18:58 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java
> +import io.github.thebusybiscuit.slimefun4.core.services.sounds.SoundEffect;
Import order

2023-06-14 18:58 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
> +import io.github.thebusybiscuit.slimefun4.core.services.sounds.SoundEffect;
Import order

2023-06-14 18:58 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/MiningTask.java
>                          furnace.getWorld().playSound(furnace.getLocation(), Sound.ENTITY_ARROW_HIT_PLAYER, 0.2F, 1F);
Todo

2023-06-16 20:58 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ElytraImpactListener.java
>                      }
its single line code so yes its missing also it doesnt matter much

2023-06-16 21:21 UTC, JustAHuman-xD requested changes
Just the one import and then I think it's good 👍

2023-06-16 21:21 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/MiningTask.java
> +import io.github.thebusybiscuit.slimefun4.core.services.sounds.SoundEffect;
import order heh.....

2023-06-16 21:29 UTC, JustAHuman-xD approved these changes
LGTM

2023-06-20 17:58 UTC, WalshyDev approved these changes
LGTM

2023-06-20 17:58 UTC, WalshyDev commented on CHANGELOG.md
> +* Added `sounds.yml` file to configure sound effects for Slimefun
duplicated

2023-06-29 11:27 UTC, JustAHuman-xD requested changes
Almost there

2023-06-29 11:27 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundEffect.java
> +import com.google.common.base.Preconditions;
Import order

2023-06-29 11:27 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundEffect.java
> -     *
Why was this removed?

2023-06-29 11:27 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundEffect.java
> -     *
?

2023-06-29 11:27 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundEffect.java
> -     *
?

2023-06-29 11:27 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundEffect.java
> +     *  @return The default volume.
?

2023-06-29 11:27 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundEffect.java
> +     *  @return The default pitch.
?

2023-06-29 11:27 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundService.java
> +import org.apache.commons.lang.Validate;
Import order

2023-06-29 11:27 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundService.java
> + *  @author TheBusyBiscuit
?

2023-06-29 11:27 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/services/sounds/SoundService.java
> -     *
?

2023-06-29 11:27 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/LongFallBoots.java
> + *  <p>
?

2023-06-29 11:27 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/LongFallBoots.java
> +     *  @return The {@link SoundEffect} played when landing
?

2023-06-29 11:27 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/MiningTask.java
> +import io.github.thebusybiscuit.slimefun4.core.services.sounds.SoundEffect;
Duplicate import?

2023-06-29 11:27 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/CoolerListener.java
> +import io.github.thebusybiscuit.slimefun4.core.services.sounds.SoundEffect;
Duplicate import

2023-06-29 11:38 UTC, JustAHuman-xD approved these changes

2023-06-29 20:08 UTC, closed without merging