withers shouldnt cause ghost bs anymore
Slimefun/Slimefun4 pull request #3697
Opened 2022-10-17 16:44 UTC by J3fftw1

## Description

This fixes withers creating ghost blockstorage blocks

Leaving it at draft now till its properly tested

## Proposed changes

added a new event and a new method

## Related Issues (if applicable)

Resolves  #3414 

## Checklist

- [] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- x ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.14.* - 1.19.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2022-10-18 13:47 UTC, TheBusyBiscuit requested changes

2022-10-18 13:47 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java
> +                removeResistantBlock(block);
This method already performs the pretty heavy lookup `BlockStorage.check`. So doing it twice FOR EVERY SINGLE block here is a huge performance drawback.

2022-10-18 13:47 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java
> +        final SlimefunItem item = BlockStorage.check(block);
No need for this to be final.

2022-10-18 13:47 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java
> +    }
Some comments would be good, specifically referencing the issue.

2023-02-23 15:29 UTC, TheBusyBiscuit commented
Closing this as stale

2023-03-25 14:49 UTC, TheBusyBiscuit requested changes

2023-03-25 14:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java
> +
```suggestion
```

2023-03-25 14:49 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java
> +                removeResistantBlock(block);
The BlockStorage check is still being made twice, you can just pass the `SlimefunItem` instance here.

2023-04-05 18:15 UTC, J3fftw1 commented
Whoops my bad this isnt stale i just completely forgot.
Will check this tomorrow.

2023-05-22 07:42 UTC, J3fftw1 commented
Could this be reviewed

2023-06-08 21:23 UTC, merged