Allow max amount of allowed waypoints to be configurable
Slimefun/Slimefun4 pull request #3730
Opened 2022-12-20 15:40 UTC by notzune

## Description

I realized that you can't configure the max amount of waypoints a player can have which would have been a helpful feature on some servers where there are restrictions on teleportation for whatever reasons they may have.

## Proposed changes

Adds a field in the config.yml that allows to change the max amount of waypoints allowed in the waypoits.yml

## Related Issues (if applicable)

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.14.* - 1.19.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2022-12-20 15:55 UTC, WalshyDev requested changes

2022-12-20 15:55 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
> -import org.bukkit.inventory.ItemStack;
Remove this change

2022-12-20 15:55 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java
> +        int maxWaypoints = settings.getInt("waypoints.max-allowed");
not a fan of this. We should probably do it under teleporter instead as an item setting

2023-01-07 12:04 UTC, TheBusyBiscuit requested changes
This would overflow the menu, wouldn't it...?

2023-03-04 10:17 UTC, Sefiraat commented
@notzune Do you intend to keep working on this PR?

2023-03-04 16:08 UTC, notzune commented
> @notzune Do you intend to keep working on this PR?

sorry, I made this quick change specifically for a friend and thought that the repo might benefit with my change but I had no intentions to try and make my change better since it worked for my friend and i'm busy with my own things. I greatly apologize

2023-03-04 16:17 UTC, Sefiraat commented
> > @notzune Do you intend to keep working on this PR?
> 
> 
> 
> sorry, I made this quick change specifically for a friend and thought that the repo might benefit with my change but I had no intentions to try and make my change better since it worked for my friend and i'm busy with my own things. I greatly apologize

No need to apologise! I will close the PR however if it's not due to be completed. Thanks regardless and you're welcome to reopen or open other PRs whenever, all welcome! <3

2023-03-04 16:18 UTC, closed without merging