added a way to set max enchants to go on an item
Slimefun/Slimefun4 pull request #3749
Opened 2023-01-21 22:21 UTC by J3fftw1

## Description

This pr adds a way to sets a limit of how many enchants can go on an item.
Default is -1 
-1 means there is no limit.

## Proposed changes

Added an item setting that checks for a limit on how many enchants can go on an item.

## Related Issues (if applicable)

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.14.* - 1.19.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2023-01-22 15:30 UTC, WalshyDev requested changes
Disenchanter?

2023-01-22 15:30 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AbstractEnchantmentMachine.java
> +    protected boolean IsEnchantmentAmountAllowed(@Nonnull ItemStack item ) {
```suggestion
    protected boolean isEnchantmentAmountAllowed(@Nonnull ItemStack item ) {
```

2023-01-22 15:30 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java
> +         * If override is false, remove those with lower level, so we don't override existing enchants
This and line below were fine before

2023-01-22 15:30 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java
> +        if (IsEnchantmentAmountAllowed(target)) {
```suggestion
        if (isEnchantmentAmountAllowed(target)) {
```

2023-01-22 15:33 UTC, J3fftw1 commented
> Disenchanter?

This is for how many enchants can go on an item.
Doesnt apply for Disenchanter imo.
Can add it if thats preferred tho

2023-01-22 15:37 UTC, Boomer-1 commented
doesn't really make sense to add it to the disenchanter.

2023-01-22 15:39 UTC, WalshyDev commented
Don't see why not. It removes enchants. We do the same for enchantment level and generally try to keep them in sync when it comes to features/settings.

2023-01-22 15:42 UTC, Boomer-1 commented
On the disenchanter, then it is set one of two ways. You can only remove an enchantment if you have less than a preset number, or if you have above a certain number. While I'd agree normally you want both the same, this one just doesn't make sense on the disenchanter. You could add it with the default of it not being applied and server owners can choose. I just don't see a use case scenario for it.

2023-03-06 19:25 UTC, J3fftw1 commented
👀

2023-03-06 20:11 UTC, JustAHuman-xD commented
Is there any display that shows this limit to the player? Otherwise I feel like that will make a lot of player confused.

2023-03-06 20:20 UTC, J3fftw1 commented
> Is there any display that shows this limit to the player? Otherwise I feel like that will make a lot of player confused.

no but that isnt the case with any limit we apply in slimefun

2023-06-08 10:05 UTC, Sfiguz7 approved these changes
LGTM

2023-06-09 08:31 UTC, svr333 approved these changes

2023-06-09 21:41 UTC, merged