Make Fire Staff not disenchantable by default
Slimefun/Slimefun4 pull request #3794
Opened 2023-03-12 00:28 UTC by Phoenix-Starlight

## Description

To make the Elemental Staff - Fire not disenchantable by default.
## Proposed changes

Creation of a Slimefun item class and altering the item setup to use this class.
This won't work with existing `Items.yml` so existing servers need to edit the file to reflect this change.
## Related Issues (if applicable)

Resolves #3768 
## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.19.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2023-03-12 11:18 UTC, TheBusyBiscuit requested changes

2023-03-12 11:18 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/staves/FireStaff.java
> +}
Could probably be generalized into `EnchantedStaff` or `EnchantedStick`

2023-03-13 13:49 UTC, TheBusyBiscuit reviewed
Sorry for making you change the name again.
What do you think about `PermanentlyEnchantedItem`?

I think that might be more indicative of the fact that it isn't just enchanted but cannot be disenchanted.

2023-03-25 14:40 UTC, TheBusyBiscuit approved these changes
LGTM

2023-03-25 17:26 UTC, svr333 approved these changes

2023-06-07 21:17 UTC, Sfiguz7 commented
Should we maybe add other items to this? Like the infused elytra

2023-06-08 20:03 UTC, Phoenix-Starlight commented
Perhaps, in my view as long as enchantments do not exceed vanilla limits
they can be disenchanted, however I understand the view where it should be
by default not dis-enchantable. (Too easy method to get enchantments etc.)

On Wed, Jun 7, 2023 at 2:17 PM Sfiguz7 ***@***.***> wrote:

> Should we maybe add other items to this? Like the infused elytra
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Slimefun/Slimefun4/pull/3794#issuecomment-1581525871>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APNXOJB5GTYJVHB2F2CONO3XKDVX7ANCNFSM6AAAAAAVXY3TEU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-08 20:33 UTC, Sfiguz7 commented
Eh I guess for the other stuff servers can still decide to change the `is_enchantable` flag in items.yml, the situation is clearly different for the fire staff since it keeps its "effects" even after being disenchanted (contrarily to armor tools and weapons).
I think this works just fine then!

2023-06-08 20:33 UTC, merged