[API] Add Display Parameter to BlockMenuPreset and BlockMenus
Slimefun/Slimefun4 pull request #3806
Opened 2023-03-22 00:55 UTC by JustAHuman-xD

## Description
Many Slimefun Blocks create menus to only convey information to the player, and they do not need to be saved or stored in memory. This will help save memory, as well as save time when saving on shutdown to help prevent the issues we see with BlockStorage taking too long and causing reverts.

## Proposed changes
This PR adds a display flag to BlockMenuPreset, thus to BlockMenu and UniversalBlockMenu.
Changes any methods involving creating new block menus in BlockStorage to check if it is display before add to memory
Changes methods in BlockMenu and UniversalBlockMenu to only save if not display

## Related Issues (if applicable)
I don't believe there are any issues

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.19.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2023-03-22 06:08 UTC, J3fftw1 requested changes

2023-03-22 06:08 UTC, J3fftw1 commented on src/main/java/me/mrCookieSlime/Slimefun/api/inventory/BlockMenu.java
> +        return display;
Can i suggest changing this do hasDisplay()

2023-03-22 06:08 UTC, J3fftw1 commented on src/main/java/me/mrCookieSlime/Slimefun/api/inventory/BlockMenu.java
> +
```suggestion

```

2023-03-22 06:08 UTC, J3fftw1 commented on src/main/java/me/mrCookieSlime/Slimefun/api/inventory/BlockMenuPreset.java
> +
```suggestion

```

2023-03-22 06:08 UTC, J3fftw1 commented on src/main/java/me/mrCookieSlime/Slimefun/api/inventory/BlockMenuPreset.java
> +
```suggestion

```

2023-03-22 06:08 UTC, J3fftw1 commented on src/main/java/me/mrCookieSlime/Slimefun/api/inventory/BlockMenuPreset.java
> +
```suggestion

```

2023-03-22 06:08 UTC, J3fftw1 commented on src/main/java/me/mrCookieSlime/Slimefun/api/inventory/BlockMenuPreset.java
> +
```suggestion

```

2023-03-22 07:55 UTC, Sefiraat commented
Has this been tested on a block set to display? Because from what I am reading with the changes here, it will stop blocks marked as display from opening their inventory on Right Click, and if that's the intent then the resolution is to just not have a BlockMenu and/or Preset?

This will stop the `hasInventory()` check functioning correctly which would likely mean a player would not be thrown out of the inventory when the block is broken etc. leaving them with an unmanaged inventory they may be able to take items out of.

At the very least we need to be able to persist inventories whilst they are loaded in the world which means means they will be in memory and thus not save any, so having them in the Map would both resolve the issues above.

The goal to speed up saving is a good one, but this can be then condensed to a more refined parameter (shouldSave?) that just skips the blockmenu being saved by checking the blockmenu when saved is called and simply not saving?

2023-03-22 10:55 UTC, JustAHuman-xD commented
> Has this been tested on a block set to display? Because from what I am reading with the changes here, it will stop blocks marked as display from opening their inventory on Right Click, and if that's the intent then the resolution is to just not have a BlockMenu and/or Preset?
> 
> This will stop the `hasInventory()` check functioning correctly which would likely mean a player would not be thrown out of the inventory when the block is broken etc. leaving them with an unmanaged inventory they may be able to take items out of.
> 
> At the very least we need to be able to persist inventories whilst they are loaded in the world which means means they will be in memory and thus not save any, so having them in the Map would both resolve the issues above.
> 
> The goal to speed up saving is a good one, but this can be then condensed to a more refined parameter (shouldSave?) that just skips the blockmenu being saved by checking the blockmenu when saved is called and simply not saving?

I had not had time to do any testing yet but wanted to open the PR that way if there were any obvious issues such as the ones you brought up I would have been able to change accordingly as I now have.

The hasInventory method could easily be updated to be fixed however the closing the inventory on block break I don't believe is which would be the glaring problem with not putting them into the map, plus like you said it is already be in memory.

I have now switched the PR to just be a "shouldSave" parameter such as you suggested and will be doing the testing tonight 👍

2023-03-25 11:42 UTC, TheBusyBiscuit requested changes
I really don't see the point of this addition.
The `BlockMenu` is just an extension of `ChestMenu` with the added functionality to save data based on location.
Why not just use a `ChestMenu` instead of making its entire functionality optional like many blocks in Slimefun do as well?

2023-03-25 14:20 UTC, JustAHuman-xD commented
> I really don't see the point of this addition. The `BlockMenu` is just an extension of `ChestMenu` with the added functionality to save data based on location. Why not just use a `ChestMenu` instead of making its entire functionality optional like many blocks in Slimefun do as well?

To put it simply, for convenience and QOL, it's easier to have a single format of doing things, when you are working with a machine that needs a saved inventory you can give it a saved inventory, if not then set saving to false. VS if you need an inventory that saves use this with this already very convenient formatting, if not use this: with not convenient formatting. It just makes it simpler for developers to develop. You said it has the added functionality of saving data based on location, but It's also just holding data, based on location. If you want to do chest menu's based on location you would have to setup your own system completely separate from Slimefun, unless you wanted to create a new ChestMenu every time they interacted with the block (such as you do in the current code for the gps control panel) which has its own added overhead and complication.

2023-03-25 14:23 UTC, JustAHuman-xD commented
> I really don't see the point of this addition. The `BlockMenu` is just an extension of `ChestMenu` with the added functionality to save data based on location. Why not just use a `ChestMenu` instead of making its entire functionality optional like many blocks in Slimefun do as well?

It is not making the entire block meu's functionality optional as you are still utilizing its per block functionality. The only difference is that it does not save to a file, everything else is still in affect.

2023-06-07 22:05 UTC, JustAHuman-xD commented
This'll be superceded by a new PR hopefully soon

2023-06-07 22:05 UTC, closed without merging