Fix android move task
Slimefun/Slimefun4 pull request #3828
Opened 2023-05-09 20:25 UTC by test137E29B

## Description

During periods of server lag, an android may no longer be where it was previously after a move was made for any reason. This prevents the task that runs on a later tick from setting the skin of the Android and causes a console error. This change wraps a check around the setSkin in the same way as Capacitor skin updating does.

Potentially could include the conversion from base64 inside the check to save some CPU in the very rare case that the Android is not actually there.

## Proposed changes

Check if the android is actually still at the block location before trying to set a skin on it.

## Related Issues (if applicable)

Resolves #3443 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.19.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2023-05-20 02:32 UTC, WalshyDev approved these changes

2023-05-20 11:52 UTC, svr333 approved these changes

2023-05-31 07:24 UTC, Sfiguz7 approved these changes
LGTM

2023-06-07 19:07 UTC, TheBusyBiscuit requested changes

2023-06-07 19:07 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
> +                }
This is literally the code at the very start of `PlayerHead.setSkin(...)` so this should not change anything and be redundant??

2023-06-07 19:08 UTC, TheBusyBiscuit commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
> +                }
Ohhh, nevermind it does the check and then throws the exception 🤦🏻‍♂️
So yeah, this checks out...

2023-06-07 19:09 UTC, TheBusyBiscuit approved these changes

2023-06-07 19:10 UTC, merged