Changed the registry to use world UUIDs
Slimefun/Slimefun4 pull request #3898
Opened 2023-07-09 11:40 UTC by J3fftw1

## Description
I have recently run into an issue where a world, when created quickly enough after deletion of a world with the same name, will not store data. I have tested this extensively and narrowed the issue down to [this](https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java#L102) ticker code and [this](https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java#L116) check for the world's existence. Since the ticker code only runs every half second, it does not remove the world from the registry until up to a Slimefun tick later and therefore causes issues in the constructor.

An easy way to recreate this issue is to delete a world and immediately create a new one with the same name.

Full credits go to @gecko10000 for some reason (my git skills most likely) his PR got closed while i tried to update it.

## Proposed changes
This PR changes the registry to use UUIDs instead of the world names themselves. This _does not_ affect the storage location in files and therefore these are not breaking changes.

This may not be the ideal way to do it; it may be better to remove the world from the registry [here](https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/WorldListener.java#L28) instead.

## Related Issues (if applicable)
No issue opened

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.14.* - 1.19.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2023-07-11 16:37 UTC, Sfiguz7 requested changes
I actually like this being a change in the underlying type as this also makes the registry more robust towards world names with dots or weird characters, which have been annoying in the past. It is simply a good idea to use unique IDs when they exists rather than compare strings.

Marking this requested changes to make sure we get it tested before it is merged

2023-07-30 10:35 UTC, variananora commented
Just tested it on 1.20.1 and it works fine.

Quick question tho, is disabling world with `.` character is still needed if we move this to UUID?

2023-07-30 10:38 UTC, J3fftw1 commented
> Just tested it on 1.20.1 and it works fine.
> 
> Quick question tho, is disabling world with `.` character is still needed if we move this to UUID?

It's bad practice anyways to use dots in file names.
Is it needed to disable with this change honestly no clue, but i think its fine to stay like this.

2023-08-01 22:03 UTC, WalshyDev requested changes

2023-08-01 22:03 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/SlimefunRegistry.java
> +    public Map<UUID, BlockStorage> getWorlds() {
People rely on this method - https://github.com/search?q=BlockStorage+.getWorlds%28%29&type=code
This will break due to signature change.

2024-11-01 20:36 UTC, closed without merging