Deny placement when deletion is queued
Slimefun/Slimefun4 pull request #3911
Opened 2023-07-18 08:24 UTC by Sefiraat

## Description
When breaking/placing blocks too quickly you can place a block and have the BlockStorage data subsequently removed resulting in loss of items. This has also caused fringe cases of blocks with multiple BlockMenus, ghost blocks and other oddities.

## Proposed changes
If a block is placed and the location is still queued for deletion, deny the block placement with a message to the player to let them know why it was denied.

This is a bit of a patch job, but a true resolution would be part of the BlockStorage rewrite and I feel is important enough to warrant a fix prior to that to ease server owners burdens.

Tested on 1.19.4 and no issues, worked as intended. But given the scope of potential effects community testing here would be wonderful :)

## Related Issues (if applicable)

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2023-07-18 08:35 UTC, J3fftw1 reviewed
Code looks good not approving till further testing.
I really want to see some things tested
Breaking blocks on 1.16 and 1.20 
Placing blocks on 1.16 and 1.20
Combination of fast placing and fast breaking since that is what this should fix

2023-07-18 11:53 UTC, JustAHuman-xD commented
I agree with Jeff but I'm wondering if there's a better message option? Idk if I was a random player I think I'd get confused by the current message.

2023-07-18 11:58 UTC, Sefiraat commented
The core elements are cannot be placed yet and try again shortly. However putting that would trigger questions as to why. The reason in the middle is boringly abstract but it is the reason and removing that part I think w

2023-07-18 12:03 UTC, Sefiraat commented on src/main/resources/languages/en/messages.yml
> +  await-deletion: '&cThis block cannot be placed yet as a previous removal has not yet been completed. Try again shortly.'
```suggestion
  await-deletion: '&cYou cannot place a Slimefun block so soon after breaking one. Try again shortly.'
```

2023-07-19 00:01 UTC, WalshyDev requested changes
Just blocking this while I understand why we even would need to do this (feels very wrong)

2023-07-19 00:22 UTC, JustAHuman-xD commented
> Just blocking this while I understand why we even would need to do this (feels very wrong)

Currently if we don't do this when someone quickly breaks and replaces Slimefun blocks it messes up blockstorage, it can cause the newly placed block to vanillize. Make chest menu items drop that shouldn't drop, can mess up a lot of stuff.

2023-07-19 00:24 UTC, WalshyDev commented
Yes, Jeff told me the same thing but that shouldn't be a problem to begin with.

2023-07-19 00:26 UTC, JustAHuman-xD commented
> Yes, Jeff told me the same thing but that shouldn't be a problem to begin with. 

I mean if it's marked for deletion, it has to wait a tick for blockstorage to clear, which neither me sefi or Jeff know why afaik. So if someone places a block before that, which adds block storage with 0 delay. That new blockstorage will be cleared. Or some blockstorage stuff merges which I have no idea why that happens.

2023-07-19 00:26 UTC, JustAHuman-xD commented
_I believe anyway if I'm mis remembering any of this that's possible but iirc this is why, a part of it anyways_

2023-07-19 01:11 UTC, Boomer-1 commented
i think originally when this was first reported it may have been someone trying to create either a dupe or some other situation, cause in order to do this, you either have to have it in your offhand and place after breaking or be insanely fast at switching your active hand.

2023-07-19 01:54 UTC, WalshyDev commented
> I mean if it's marked for deletion, it has to wait a sf tick for blockstorage to clear, which neither me sefi or Jeff know why afaik. 

yeah this shouldn't be a thing. That would just cause problems. So I want to understand if that is what is happening, understand why and understand if we do need that (i highly doubt it)

We never used to do that so the fact we do now is a problem. I want to fix the root of the problem not monkey patch on top.

2023-07-19 05:48 UTC, Sefiraat commented
Seriously? 

The reason I have not tackled the tick delay is because I asked you specifically in voice chat and you told me definitively that the tick delay in the queue deletion could not be changed. You didn’t give a shadow of a doubt in your response and said it could only be cleared as part of the blockstorage rewrite. Once again work is undertaken to provide relief while we await/work on the larger problems and you only question it AFTER a PR is raised, AFTER time is invested. Cmon Walshy you know how precious time is. 

Moreover this is a big problem on servers and has been for sometime and this is now causing problems with addon development as bad signals are being sent to addon so unless you have the answer to your questions above and you can confidently say the delay can be removed without causing issues, then we should absolutely patch the current issue while you work on the ‘true fix’ and feel free to remove this patch when completed. It is absolutely absurd to me that you’re happy to leave this in when we can provide this fix now when you do not know when/how your understanding of the fuller fix will come.

2023-07-19 06:41 UTC, Sefiraat commented
> > I mean if it's marked for deletion, it has to wait a sf tick for blockstorage to clear, which neither me sefi or Jeff know why afaik.
> 
> yeah this shouldn't be a thing. That would just cause problems. So I want to understand if that is what is happening, understand why and understand if we do need that (i highly doubt it)
> 
> We never used to do that so the fact we do now is a problem. I want to fix the root of the problem not monkey patch on top.

As a side note, I've checked the git logs for both little spans of code and it's awaited the ticker to run the deletion all the way back to 2016, unless I have missed something.

2023-07-19 07:17 UTC, J3fftw1 commented
Here is where the 1 tick delay happens.
https://github.com/Slimefun/Slimefun4/blob/dc22e6658990dd7912dabbbfb79a0a24050eed74/src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java#L611

2023-07-19 12:47 UTC, Sefiraat commented
Tested on 1.17.1, 1.18.2, 1.19.4 and 1.20 with no differences in behaviour, though to be expected given there is nothing version specific within this code.

2023-07-26 15:24 UTC, J3fftw1 approved these changes

2023-08-10 13:25 UTC, JustAHuman-xD approved these changes
I think this is still a really necessary merge before the blockstorage rewrite is finished

2023-11-22 23:48 UTC, Boomer-1 commented
in my testing this seems to be patched. i got the error message as intended and could not duplicate the original error after a dozen + attempts using various sf blocks.

2023-11-24 16:49 UTC, test137E29B commented
Would like to add this is very much needed - on servers with lots of people using slimefun, pending actions I've seen up to 5 million. This causes a lot of slimefun machines, or addon slimefun blocks like Sefi's network to turn into vanilla blocks. This is really annoying honestly as it can even happen over a forced server restart where not all pending actions are completed, or desync in some other way.

The amount of time invested into fixing these issues by server staff is insane, and especially on servers where hoppers are not craftable, it makes using Sefi's networks really frustrating since you can't just craft another grabber or pusher and replace it yourself. This temporary fix would solve the issues that players have, while being much less annoying to wait a little knowing it's not going to break the moment it's placed or at a random time in future.

2023-11-24 16:57 UTC, JustAHuman-xD commented
As someone who is constantly dealing with the ramifications of this I completely agree, this would help us sooooo much T>T

2023-11-24 18:04 UTC, WalshyDev requested changes

2023-11-24 18:04 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
> +                    e.setCancelled(true);
We need to get out of here. We don't want to call SlimefunBlockPlaceEvent, we're currently still even writing to block storage and block data.

```suggestion
                    e.setCancelled(true);
                    return;
```

2023-11-24 20:06 UTC, WalshyDev commented
I understand what is going on now and am fine with this going ahead.

@J3fftw1 fixed up the bad behaviour and we've added some new tests
I'd like it re-tested before I'm comfortable being ok to merge

Thanks @Sefiraat

2023-11-24 20:13 UTC, J3fftw1 approved these changes

2023-11-24 20:21 UTC, Boomer-1 commented
on the second preview build, it is working as intended without the warning message, which feels much cleaner. i placed multiple blocks with the offhand the moment the main hand broke a block and all seemed to be working without any issue. I tested a dozen core slimefun machines and 5-6 from addons and not once did the item break

2023-11-24 20:25 UTC, JustAHuman-xD commented
> on the second preview build, it is working as intended without the warning message, which feels much cleaner. i placed multiple blocks with the offhand the moment the main hand broke a block and all seemed to be working without any issue. I tested a dozen core slimefun machines and 5-6 from addons and not once did the item break

there should still be a warning message, if you didnt ever get any it means you never placed when deletion was queued

2023-11-24 20:28 UTC, Boomer-1 commented
well, i can't place it any faster than it is. any suggestions? or when is it being queued? is there at least a tick delay?

2023-11-24 20:29 UTC, JustAHuman-xD commented
easiest way would be to test it on some server with alot of lag

2023-11-24 20:30 UTC, WalshyDev commented
It's 1 Slimefun tick so you can make it super slow
`config.yml` -> `URID.custom-ticker-delay`

2023-11-24 20:30 UTC, Boomer-1 commented
got a live production server owner who would be willing to add it to test?

2023-11-24 20:32 UTC, Boomer-1 commented
> It's 1 Slimefun tick so you can make it super slow `config.yml` -> `URID.custom-ticker-delay` change to like 100

i'm reloading the server with it set to 100 to see what happens

2023-11-24 20:38 UTC, Boomer-1 commented
over a dozen attempts and still no message

2023-11-24 20:39 UTC, Boomer-1 commented
ok finally got it after a few more

2023-11-24 20:41 UTC, Boomer-1 commented
after getting the message, all sf machines continued to work as expected

2023-11-24 21:15 UTC, JustAHuman-xD approved these changes

2023-11-24 21:38 UTC, WalshyDev approved these changes
Alright, @Boomer-1 managed to confirm this behaviour is indeed broken in the latest build and cannot break here (ty Boomer).

I'm happy for this now

2023-11-24 21:40 UTC, merged