Add MultiBlockCraftEvent (Updated version of #3439)
Slimefun/Slimefun4 pull request #3928
Opened 2023-07-29 22:50 UTC by JustAHuman-xD

## Description
Making this PR to resolve the Merge Conflicts of #3439 and change some aspects of the PR

## Proposed changes
- Added `MultiBlockCraftEvent` an event called whenever a player uses a core slimefun multiblock to craft something
  - It is cancellable and provides the listener with the player, machine, inputs and output
  - a listener can also set the output if they so desire
- Changed all relevant classes to use `MultiBlockCraftEvent`

## Related Issues (if applicable)

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2023-07-29 22:58 UTC, J3fftw1 requested changes

2023-07-29 22:58 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java
> +import io.github.thebusybiscuit.slimefun4.api.events.MultiBlockCraftEvent;
import order :P

2023-07-29 22:58 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/GrindStone.java
> +import io.github.thebusybiscuit.slimefun4.api.events.MultiBlockCraftEvent;
import order :P

2023-07-29 22:58 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Juicer.java
> +import io.github.thebusybiscuit.slimefun4.api.events.MultiBlockCraftEvent;
import order :P

2023-07-29 22:58 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java
> +import io.github.thebusybiscuit.slimefun4.api.events.MultiBlockCraftEvent;
import order :P

2023-07-29 22:58 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreCrusher.java
> +import io.github.thebusybiscuit.slimefun4.api.events.MultiBlockCraftEvent;
import order :P

2023-07-29 22:58 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/OreWasher.java
> +import io.github.thebusybiscuit.slimefun4.api.events.MultiBlockCraftEvent;
import order

2023-07-29 22:58 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/PressureChamber.java
> +import io.github.thebusybiscuit.slimefun4.api.events.MultiBlockCraftEvent;
import order :P

2023-07-29 22:58 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/TableSaw.java
> +import io.github.thebusybiscuit.slimefun4.api.events.MultiBlockCraftEvent;
import order :P

2023-07-29 23:03 UTC, J3fftw1 approved these changes

2023-07-31 05:29 UTC, variananora commented
How should I approach to test this? I'm quite confused on how to tested this in game without any third party plugin that cancel/modify stuff

2023-07-31 05:32 UTC, JustAHuman-xD commented
> How should I approach to test this? I'm quite confused on how to tested this in game without any third party plugin that cancel/modify stuff

Tomorrow I can see if I have time to make a plug-in to test this all with, for now you could just test that i didn't break anything just by adding the events?

2023-07-31 05:34 UTC, variananora commented
Okay will do two part testing then, the first one being the gameplay functionality is still intact and working and the second one is being the API can be called correctly. Thanks JustAHuman

2023-07-31 05:35 UTC, JustAHuman-xD commented
> Okay will do two part testing then, the first one being the gameplay functionality is still intact and working and the second one is being the API can be called correctly. Thanks JustAHuman

No problem! Thanks for all of the testing it's honestly a god send 👏👏👏

2023-08-01 05:46 UTC, variananora commented
Just tested this on 1.20.1 and it works flawlessly!

[Here](https://cdn.discordapp.com/attachments/1135126914529513513/1135810278697730088/SlimefunTest-1.0-SNAPSHOT.jar) is a little plugin that I created to listen the event. `/slimefuntest` to change cancel event or change the output

Video: https://youtu.be/KeFTSsPqJZo

2023-08-01 06:03 UTC, JustAHuman-xD commented
> Just tested this on 1.20.1 and it works flawlessly!
> 
> 
> 
> [Here](https://cdn.discordapp.com/attachments/1135126914529513513/1135810278697730088/SlimefunTest-1.0-SNAPSHOT.jar) is a little plugin that I created to listen the event. `/slimefuntest` to change cancel event or change the output
> 
> 
> 
> Video: https://youtu.be/KeFTSsPqJZo

Oh my gosh I completely forgot about this I'm sorry! Looks like you did it yourself which is awesome but sorry I forgot

2023-08-01 06:06 UTC, variananora commented
> Oh my gosh I completely forgot about this I'm sorry! Looks like you did it yourself which is awesome but sorry I forgot

It's okay! It's an opportunity for me to code in Java and Spigot-API thinggy tho, lol

2023-09-03 10:17 UTC, Sefiraat approved these changes
👍

2023-11-21 20:07 UTC, merged