Feature/block drop creative
Slimefun/Slimefun4 pull request #3934
Opened 2023-08-05 21:22 UTC by TheSilentPro

## Description
Allows owners to configure whether slimefun blocks should drop when broken by players in creative mode.

## Proposed changes
Added a creative and config check when dropping sf block.

## Related Issues (if applicable)
n/a

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2023-08-05 21:49 UTC, J3fftw1 requested changes

2023-08-05 21:49 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java
> +                        if (e.getPlayer().getGameMode() == GameMode.CREATIVE && Slimefun.getCfg().getBoolean("options.drop-block-creative")) {
```suggestion
                        if (e.getPlayer().getGameMode() != GameMode.CREATIVE || Slimefun.getCfg().getBoolean("options.drop-block-creative")) {
```

2023-09-03 10:21 UTC, Sefiraat approved these changes
👍 pending testing, though it's simple enough it shouldn't need much xD

2023-09-06 14:03 UTC, JustAHuman-xD approved these changes
LGTM

2023-11-23 00:18 UTC, Boomer-1 commented
this appears to be working as intended. both config options worked as outlined.

2023-12-31 08:56 UTC, J3fftw1 approved these changes

2023-12-31 08:58 UTC, merged