Fixes duplication glitch with explosive tools in combination with itemsadder
Slimefun/Slimefun4 pull request #3940
Opened 2023-08-08 15:29 UTC by J3fftw1

## Description

This PR resolves a duplication glitch with the Items adder plugin and Slimefun.

## Proposed changes

Disable blockbreak when its a custom block from items adder.

## Related Issues (if applicable)

Resolves #3836 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2023-08-08 15:30 UTC, J3fftw1 commented
keeping this on draft for now.
Looking into a way to allow itemsadder blocks to be broken as well.
Comment is standing out in https://github.com/PluginBugs/Issues-ItemsAdder/issues/2777

2023-08-08 15:53 UTC, J3fftw1 commented
Sadly there doesnt seem to be away for us to actually drop the itemsadder block. This will be a sufficient fix for now. I do want to look into this more but that will be a follow up PR.

2023-08-14 15:39 UTC, TheBusyBiscuit requested changes
This will cause a ClassNotFoundException on every server that does not use ItemsAdder :NotLikeThis:

2023-09-03 16:10 UTC, JustAHuman-xD submitted a review, later dismissed
LGTM (as much as it can, im not familiar with itemsadder api so 🤷, but the code itself is fine)

2023-09-03 21:58 UTC, iTwins commented
Don't know if it's possible, but if it is wouldn't the 'right' place to handle this be in the integrations package?

2023-09-04 08:29 UTC, J3fftw1 commented
> Don't know if it's possible, but if it is wouldn't the 'right' place to handle this be in the integrations package?

good catch

2023-09-06 09:48 UTC, Sfiguz7 approved these changes
Same as above, trusting the API to be correct I don't see any issues

2023-09-06 11:11 UTC, JustAHuman-xD approved these changes
LGTM same as sfiguz

2023-09-06 13:31 UTC, merged