Update ButcherAndroidListener.java
Slimefun/Slimefun4 pull request #4007
Opened 2023-10-25 14:48 UTC by Kub94ekCZ

Fixed bug with emerald drop from vindicators when killed by Butcher Android

## Description

I'm making this pull request to fix the bug with vindicators don't drop emeralds when killed by Butcher Android

## Proposed changes

I just added code to fix the bug

## Related Issues (if applicable)

Resolves #3849 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2023-10-25 15:01 UTC, JustAHuman-xD approved these changes
We need to change this system but that's out of scope, LGTM

2023-11-21 13:46 UTC, JustAHuman-xD requested changes

2023-11-21 13:46 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ButcherAndroidListener.java
> +            drops.add(new Itemstack(Material.EMERALD, 1 + random.nextInt(2)));
Need to capitalize stack
```suggestion
            drops.add(new ItemStack(Material.EMERALD, 1 + random.nextInt(2)));
```

2023-11-21 13:48 UTC, JustAHuman-xD approved these changes
LGTM (we ignore i missed that previously)

2023-12-06 13:49 UTC, Sfiguz7 approved these changes

2023-12-06 13:49 UTC, merged