Add TalismanActivateEvent (Updated version of #3920)
Slimefun/Slimefun4 pull request #4045
Opened 2023-12-07 20:27 UTC by JustAHuman-xD

## Description
I've made this pull request to update and apply some suggestions from #3920 
I also have a couple of ideas of things to add to the PR but I'm going to ask for opinions on those beforehand

## Proposed changes
- Added the `TalismanActivateEvent`
 - Extends `PlayerEvent` and implements `Cancellable` 
 - Called when any talisman is activated by the `Talisman#activateTalisman` event
 - Contains The `Player`, `Talisman`, and `ItemStack` used when activating a talisman
- In `Talisman#activateTalisman` call the new event, if it's not cancelled, do all normal operations

## Related Issues (if applicable)
N/A

## Checklist
- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2023-12-07 20:29 UTC, JustAHuman-xD commented
The couple of ideas I had that I wanted opinions on:
- Adding a field to the event that controls whether or not the talisman should be consumed
- (I had another one but have currently forgotten it)

2023-12-07 22:45 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/events/TalismanActivateEvent.java
> +
```suggestion
```

2023-12-08 20:56 UTC, Sfiguz7 requested changes
Requesting change as I don't see a reason not to add the optional preventConsumption flag.  Adding a test request while I am at it

EDIT: forgot the needs testing is added by default, less work for me

2023-12-08 23:30 UTC, Sfiguz7 submitted a review, later dismissed
Spent some time in VC and all looks good, especially the tests <3

2023-12-09 07:43 UTC, J3fftw1 commented
can we also have tests that the endertalisman doesnt work in a normal inventory and for the normal talisman not to work in an enderchest

2023-12-12 20:27 UTC, Sfiguz7 commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java
> +    }
```suggestion
        // Assert the normal talisman does not activate in the ender chest
        activateAnvilTalisman(false, true);
        try {
            server.getPluginManager().assertEventFired(TalismanActivateEvent.class, ignored -> true);
        } catch (AssertionError ignored) {
            return; // This is expected; the event should not have fired
        }
        server.getPluginManager().clearEvents();

        // Assert the ender talisman does not activate in the inventory
        try {
            activateAnvilTalisman(true, false);
            server.getPluginManager().assertEventFired(TalismanActivateEvent.class, ignored -> true);
        } catch (AssertionError ignored) {
            return; // This is expected; the event should not have fired
        }
        server.getPluginManager().clearEvents();
    }
```

2023-12-12 20:28 UTC, Sfiguz7 submitted a review, later dismissed

2023-12-12 20:31 UTC, Sfiguz7 commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java
> +        activateAnvilTalisman(false);
```suggestion
        activateAnvilTalisman(false, false);
```

2023-12-12 20:31 UTC, Sfiguz7 commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java
> +        activateAnvilTalisman(true);
```suggestion
        activateAnvilTalisman(true, true);
```

2023-12-12 20:31 UTC, Sfiguz7 commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java
> +        activateAnvilTalisman(false);
```suggestion
        activateAnvilTalisman(false, false);
```

2023-12-12 20:31 UTC, Sfiguz7 commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java
> +        activateAnvilTalisman(true);
```suggestion
        activateAnvilTalisman(true, true);
```

2023-12-12 20:31 UTC, Sfiguz7 commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java
> +        activateAnvilTalisman(false);
```suggestion
        activateAnvilTalisman(false, false);
```

2023-12-12 20:31 UTC, Sfiguz7 commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java
> +        activateAnvilTalisman(true);
```suggestion
        activateAnvilTalisman(true, true);
```

2023-12-12 20:33 UTC, Sfiguz7 commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java
> +        server.getPluginManager().callEvent(event);
```suggestion
    void activateAnvilTalisman(boolean enderVariant, boolean inEnderChest) {
        player.getInventory().clear();
        player.getEnderChest().clear();

        ItemStack talismanItem = enderVariant ? enderTalisman.getItem() : talisman.getItem();
        ItemStack breakableItem = new ItemStack(Material.IRON_PICKAXE);

        if (inEnderChest) {
            player.getEnderChest().addItem(talismanItem);
        } else {
            player.getInventory().addItem(talismanItem);
        }

        player.getInventory().setItemInMainHand(breakableItem);

        PlayerItemBreakEvent event = new PlayerItemBreakEvent(player, breakableItem);
        server.getPluginManager().callEvent(event);
```

2023-12-12 20:36 UTC, Sfiguz7 commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java
> +        activateAnvilTalisman(false);
```suggestion
        activateAnvilTalisman(false, false);
```

2023-12-12 20:36 UTC, Sfiguz7 commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestTalismanActivateEvent.java
> +        activateAnvilTalisman(true);
```suggestion
        activateAnvilTalisman(true, true);
```

2023-12-12 20:42 UTC, Sfiguz7 approved these changes
Don't worry about the list of commits above, for some reason I was unable to push to Justin's fork and I am an impatient blueberry so I copied over my changes a piece at a time. Also didn't know about batch committing suggested changes so there you go

2023-12-12 20:49 UTC, J3fftw1 approved these changes
Looks good to alessio

2023-12-12 20:51 UTC, merged