Remove Unirest and replace with Java's native HttpClient
Slimefun/Slimefun4 pull request #4068
Opened 2023-12-21 06:53 UTC by WalshyDev

## Description
When we first implemented Unirest, the goal was always to remove it once we moved to Java 11 minimum. It's been a while since this happened so let's do this.

This reduces the jar size from 4.7 MB (4782834 bytes) to 2.4 MB (2480486 bytes) so we remove ~2.3 MB.

## Proposed changes
Removes Unirest with Java's native HttpClient (introduced in Java 11)

## Related Issues (if applicable)
N/A

## Checklist
- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2023-12-21 16:01 UTC, J3fftw1 requested changes
please create unit tests

2023-12-27 21:00 UTC, WalshyDev commented
This code cannot be unit tested, it's all private or ran as part of a task. Making it public doesn't make sense here

2023-12-27 21:02 UTC, J3fftw1 submitted a review, later dismissed

2024-01-17 16:13 UTC, J3fftw1 approved these changes

2024-02-25 17:10 UTC, Sfiguz7 approved these changes

2024-02-25 18:24 UTC, merged