add new recipe api
Slimefun/Slimefun4 pull request #4093
Opened 2024-01-15 19:06 UTC by SchnTgaiSpock

## Description
This PR supercedes #4078

### Description from #4078
Hey guys, this is my attempt at the recipe rewrite.

I have written up an [ADR](https://github.com/Slimefun/Slimefun4/pull/4078/files#diff-b225a6f01a4a9496f99a188c0b09c59baf6d37c96c7185cc174bc73a2f528e35) that goes over how the new API currently works, but in short:
- Recipe system sucks
- Can't translate recipes in the dispenser (like crafting Copper Wire on the top row)
- Items can only have one* recipe (mostly)
- Can't have true shapeless recipes

Any feedback on the API or discussion around the new recipe system in general would be greatly appreciated!

## Proposed changes
- Adds a new recipe API which:
  - Allows recipe inputs with multiple options (e.g. Vanilla/Slimefun Copper)
  - Allows true shaped/shapeless recipes (does not replace the old versions)
  - Allows machines and workstations to search recipes more efficiently
  
## Related Issues (if applicable)
N/A

## Checklist
- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2024-01-15 19:09 UTC, J3fftw1 requested changes
Can we get unit tests on this?

2024-01-15 19:09 UTC, SchnTgaiSpock commented
yup thats my prio rn

2024-01-15 19:26 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +     * This service is responsible for finding/identifying {@link org.bukkit.inventory.Recipe Recipes}
Please import this

2024-01-15 23:35 UTC, SchnTgaiSpock commented
unit tests should be done, if i missed something lmk

2024-03-21 12:53 UTC, JustAHuman-xD commented
Might be worth waiting for the item stack component changes before doing much more with this

2024-11-04 02:54 UTC, closed without merging