:sparkles: feat(api): Introduce SlimefunItemRegistryFinalizedEvent
Slimefun/Slimefun4 pull request #4099
Opened 2024-01-17 09:02 UTC by ProfElements

## Description

This Event is provided so that plugins that have integrations with each other aren't stuck in a state in which some SlimefunItems may not be available to one plugin or the other.

I will use this event to provide a cleaner integration between Dynatech and other plugins. Currently InfinityXpansion, ExoticGarden, and Gastronomicon.

## Proposed changes

Make an event to be able to listen to Slimefun's Registry finalizing all static items. 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [x] I added sufficient Unit Tests to cover my code.

2024-01-17 09:05 UTC, J3fftw1 commented
Can we get unit tests?

2024-01-17 10:36 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/events/SlimefunRegistryFinalizedEvent.java
> + * {@link SlimefunItem} registry before auto loading
"before auto loading"
before auto loading what?

2024-01-17 10:36 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/PostSetup.java
> +        Bukkit.getPluginManager().callEvent(new SlimefunRegistryFinalizedEvent());
Seems like a bit of a strange place to put this call, any reason it's not higher up? Either right under item load or right under the recipe load.

2024-01-17 10:36 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/events/SlimefunRegistryFinalizedEvent.java
> +public class SlimefunRegistryFinalizedEvent extends Event {
```suggestion
public class SlimefunItemRegistryFinalizedEvent extends Event {
```

2024-01-17 11:07 UTC, ProfElements commented
Fixed up according to suggestions

2024-01-17 11:36 UTC, JustAHuman-xD commented
I'm not sure about the use case of this tbch, for example: if one addon waits for this event to then register its items to integrate with another addon, but then *another* addon waits for this event to integrate with that addon, then you would still have the same problem.

Currently if you soft depend on any addon you can utilize its items without any problem, in my experience anyways. I guess it depends on the addon but I've never experienced that not working.

The use case you have also provided encourages registering items, after load items is called, which feels wrong. 

Idk this could just be me but I don't think this is the right solution.

2024-01-17 11:44 UTC, JustAHuman-xD requested changes

2024-01-17 11:44 UTC, JustAHuman-xD commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/PostSetup.java
> +
```suggestion
```

2024-01-17 11:44 UTC, JustAHuman-xD commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunRegistryFinalizedEvent.java
> +
```suggestion
```

2024-01-17 11:44 UTC, JustAHuman-xD commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunRegistryFinalizedEvent.java
> +
```suggestion
```

2024-01-17 11:44 UTC, JustAHuman-xD commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunRegistryFinalizedEvent.java
> +import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
Static imports are against the code style guidelines ([See here](https://github.com/Slimefun/Slimefun4/blob/master/CONTRIBUTING.md#1-imports))

2024-01-17 12:02 UTC, ProfElements commented
> I'm not sure about the use case of this tbch, for example: if one addon waits for this event to then register its items to integrate with another addon, but then _another_ addon waits for this event to integrate with that addon, then you would still have the same problem.
> 
> Currently if you soft depend on any addon you can utilize its items without any problem, in my experience anyways. I guess it depends on the addon but I've never experienced that not working.
> 
> The use case you have also provided encourages registering items, after load items is called, which feels wrong.
> 
> Idk this could just be me but I don't think this is the right solution.

This probably isn't the right solution, but I'm currently in the situation when I want to integrate items into another project. Which I can't load after because its `softdepend` on DynaTech. I don't thing we should add items to registry after this point, I'm using it to add all my recipes using another projects items IE my SeedPlucker adding Gastro Seeds to its recipes

2024-01-17 12:07 UTC, JustAHuman-xD commented
> This probably isn't the right solution, but I'm currently in the situation when I want to integrate items into another project. Which I can't load after because its `softdepend` on DynaTech. I don't thing we should add items to registry after this point, I'm using it to add all my recipes using another projects items IE my SeedPlucker adding Gastro Seeds to its recipes


Ah so you're in a circular dependency problem. Which is similar to the issue I showed with this. One solution I can think of is you PR to gastro and make gastro add it to the seed plucker but yeah I get the problem.

I think what you may be able to do is something kinda like slimefun, slimefun adds a lot of recipes **to machines** on post register. So if all you want to do is add machine recipes, then this event is actually a good solution. In which case I misunderstood what this was meant for. I thought you meant registering items dependent on addons items 😅

2024-01-17 12:11 UTC, ProfElements commented
Yeah Im sorry i know my explanation was kinda confusing

2024-01-17 13:00 UTC, JustAHuman-xD submitted a review, later dismissed
LGTM, apologizes for the confusion 😅

2024-01-17 13:02 UTC, JustAHuman-xD reviewed
(You double removed the empty line here, not a big deal I'll re add it lol)

2024-01-17 13:02 UTC, JustAHuman-xD commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunRegistryFinalizedEvent.java
> +    @Test
```suggestion

    @Test
```

2024-01-17 13:05 UTC, JustAHuman-xD approved these changes
LGTM

2024-01-17 15:13 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/events/SlimefunItemRegistryFinalizedEvent.java
> +
```suggestion
```

2024-01-17 15:13 UTC, WalshyDev commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/events/SlimefunItemRegistryFinalizedEvent.java
> + * {@link SlimefunItem} registry.
```suggestion
 * {@link SlimefunItem} registry. We recommend listening to this event if you
 * want to register recipes using items from other addons.
```

2024-01-17 16:14 UTC, J3fftw1 submitted a review, later dismissed

2024-01-18 10:58 UTC, WalshyDev commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunRegistryFinalizedEvent.java
> +        //Make sure post setup does not throw
```suggestion
        // Make sure post setup does not throw
```

2024-01-18 10:58 UTC, WalshyDev commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunRegistryFinalizedEvent.java
> +        //Make sure post setup sent the event
```suggestion
        // Make sure post setup sent the event
```

2024-01-18 10:58 UTC, WalshyDev commented on src/test/java/io/github/thebusybiscuit/slimefun4/api/events/TestSlimefunRegistryFinalizedEvent.java
> +
```suggestion
```

2024-01-18 10:59 UTC, WalshyDev approved these changes

2024-01-18 10:59 UTC, J3fftw1 approved these changes

2024-01-18 14:07 UTC, merged