chore: add rc warnings to `sf versions` command
Slimefun/Slimefun4 pull request #4129
Opened 2024-02-14 16:11 UTC by ybw0014

## Description

People who use RC versions still report bugs to Discord/GitHub, adding warning messages may possibily stop them from reporting. (just possible, people without eyes will still report)
Also fixed a issue introduced in https://github.com/Slimefun/Slimefun4/pull/4096, where all the text after updater available have hover event.

This will only apply to future RC versions.

Test run (I changed the version manually to RC - 38):
![image](https://github.com/Slimefun/Slimefun4/assets/7105953/d4c66b24-2bb4-4305-974f-694fcc4d1e57)

## Proposed changes

Add warning messages to `/sf versions`.

## Related Issues (if applicable)

N/A

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2024-02-14 16:15 UTC, ybw0014 commented
Where else we can add warning messages? maybe the version in sf guide?

2024-02-14 20:19 UTC, JustAHuman-xD commented
I think we should re-word this, “we don’t provide support for stable versions” won’t make sense to 99% of people if they don’t know RC is meant for plugin developers.

2024-02-15 19:34 UTC, J3fftw1 requested changes

2024-02-15 19:34 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/core/commands/subcommands/VersionsCommand.java
> +                        "We do not provide support for stable versions, use with caution!\n" +
Why `use with caution!` this is a stable build there should be no worries.
I get what you mean but i dont think this is the way to say it

2024-02-15 19:36 UTC, J3fftw1 commented
> Where else we can add warning messages? maybe the version in sf guide?

on the guide settings for players maybe.

Im in general not a huge fan of giving a warning.
reports for RC should always be treated with a grain of salt since it can be fixed in dev versions as we see  99% of the time.
But we have gotten valid reports on stable versions.
Im not gonna put a blocker on it since i know many like this

2024-02-18 00:08 UTC, ybw0014 commented
if you don't want such messages I will turn this into a bug fix PR.

2025-10-13 20:48 UTC, closed without merging