Fix ChargingBench
Slimefun/Slimefun4 pull request #4184
Opened 2024-05-03 17:10 UTC by Intybyte

## Description

Making ChargingBench rechargeable only ItemStacks with 1 items

## Proposed changes

By adding this feature addon makers can make heir own Rechargeable any item they want and not be limited to tools

## Related Issues (if applicable)

Resolves  #4183

## Checklist

- [V] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [V] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [V] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [V] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2024-05-04 09:00 UTC, J3fftw1 requested changes

2024-05-04 09:00 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ChargingBench.java
> +
```suggestion
            if (item == null) {
                continue;
            }

            if (item.getAmount() != 1) {
                continue;
            }

```

2024-05-10 18:05 UTC, J3fftw1 approved these changes
LGTM

2024-05-30 19:36 UTC, JustAHuman-xD commented
I did not want to dismiss the review aaaa

2024-05-30 19:40 UTC, JustAHuman-xD approved these changes
LGTM

2024-08-08 16:44 UTC, TheBusyBiscuit approved these changes
LGTM

2024-08-08 16:45 UTC, merged