Update README.md
Slimefun/Slimefun4 pull request #4222
Opened 2024-08-12 22:25 UTC by Boomer-1

## Description

updating the readme to show the current version cap of 1.20.4

## Proposed changes

simply changing 1.20.x to read 1.20.4 until we update to the latest version

## Related Issues (if applicable)

## Checklist

- [x ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [ x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2024-08-12 22:29 UTC, ybw0014 requested changes

2024-08-12 22:29 UTC, ybw0014 commented on README.md
> +| **Minecraft version(s)** | :video_game: **1.16.\* - 1.20.4\*** | :video_game: **1.16.\* - 1.20.4\*** |
```suggestion
| **Minecraft version(s)** | :video_game: **1.16.\* - 1.20.4** | :video_game: **1.16.\* - 1.20.4** |
```

the `\*` is used to display a *.

2024-08-13 06:34 UTC, J3fftw1 submitted a review, later dismissed

2024-08-14 03:23 UTC, JustAHuman-xD approved these changes

2024-09-06 12:13 UTC, Sfiguz7 approved these changes
It's been hanging for so long that at this point we might as well correct it I guess

2024-09-06 18:17 UTC, ybw0014 commented
need to change a line of code to make CI check pass

2024-09-06 18:41 UTC, Sfiguz7 commented on README.md
> +| **Minecraft version(s)** | :video_game: **1.16.\* - 1.20.4** | :video_game: **1.16.\* - 1.20.4** |
```suggestion
| **Minecraft version(s)** | :video_game: **1.16.\* - 1.20.4** | :video_game: **1.16.\* - 1.20.4** | 
```

2024-09-06 18:44 UTC, Sfiguz7 commented
Wait, you mean a line of the source code, right?

2024-09-06 21:18 UTC, ybw0014 commented
yeah a line of the source code

2024-09-12 23:32 UTC, ybw0014 commented
This can be closed when #4186 is merged.

2024-09-15 06:21 UTC, ybw0014 commented
this can be closed

2024-09-15 11:10 UTC, WalshyDev commented
Ez

2024-09-15 11:10 UTC, closed without merging