new ItemStack => ItemStack.of
Slimefun/Slimefun4 pull request #4246
Opened 2024-09-25 18:38 UTC by Intybyte

## Description
Use `ItemStack.of` instead of `new ItemStack`

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2024-09-25 18:47 UTC, ybw0014 requested changes
this would break backward compatibility, add version check

2024-09-25 18:50 UTC, Intybyte commented
> this would break backward compatibility, add version check

i completely forgot about that, on it

2024-09-25 20:21 UTC, Intybyte commented
Applied to everything beside test enviroment for now

2024-09-26 02:29 UTC, md5sha256 approved these changes
LGTM

2024-09-26 10:14 UTC, Intybyte commented
Maybe it is better if I move the StackResolver to the compatibility` package, didn't know such a package exists already, should i call it `VersionedItemStack`?

2024-09-30 19:17 UTC, Intybyte commented
Running with a local fork of MockBukkit

2024-10-01 20:13 UTC, ybw0014 requested changes

2024-10-01 20:13 UTC, ybw0014 commented on src/main/java/io/github/thebusybiscuit/slimefun4/api/MinecraftVersion.java
>       * This constant represents an exceptional state in which we were unable
duplicated

2025-03-09 12:46 UTC, closed without merging